### ISSUE TITLE
Activity Provider not updating locations as per interval

### ISSUE THREAD

**Issue by shyamal890** [mauron85/cordova-plugin-background-geolocation#115]
It seems that sometimes when the app is killed and background service kicks in, location updates are not sent as per interval set.

This is what I got with `adb logcat`

```
07-14 01:35:46.110  3004  3004 D FusedLocationProvider: onLocationChanged: Location[mProvider=fused,mTime=1468440346092,mLatitude=23.0376063,mLongitude=72.5295694,mHasAltitude=false,mAltitude=0.0,mHasSpeed=false,mSpeed=0.0,mHasBearing=false,mBearing=0.0,mHasAccuracy=true,mAccuracy=1018.0,mExtras=null]
07-14 01:35:46.110  3004  6444 D LocationService: Executing PostLocationTask#doInBackground
07-14 01:35:46.110  3004  6444 D LocationService: Posting json to url: http://api.address.io//api/Location/AddMauron85Locations/eb438907f91a0e88/GT-I8552 headers: {Authorization=Bearer sdadssad}
07-14 01:35:46.120  3004  6444 W BGPlugin: Exception posting json: java.net.SocketException: sendto failed: ECONNRESET (Connection reset by peer)
07-14 01:35:46.120  3004  6444 W System.err: java.net.SocketException: sendto failed: ECONNRESET (Connection reset by peer)
07-14 01:35:46.240  3004  6444 W System.err:    at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:506)

07-14 01:35:46.240  3004  6444 W System.err:    at libcore.io.IoBridge.sendto(IoBridge.java:475)
07-14 01:35:46.250  3004  6444 W System.err:    at java.net.PlainSocketImpl.write(PlainSocketImpl.java:508)
07-14 01:35:46.250  3004  6444 W System.err:    at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:46)

07-14 01:35:46.250  3004  6444 W System.err:    at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:270)
07-14 01:35:46.250  3004  6444 W System.err:    at java.io.BufferedOutputStream.flushInternal(BufferedOutputStream.java:185)
07-14 01:35:46.250  3004  6444 W System.err:    at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:85)
07-14 01:35:46.250  3004  6444 W System.err:    at libcore.net.http.FixedLengthOutputStream.flush(FixedLengthOutputStream.java:49)
07-14 01:35:46.250  3004  6444 W System.err:    at java.io.OutputStreamWriter.flushBytes(OutputStreamWriter.java:171)
07-14 01:35:46.250  3004  6444 W System.err:    at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:158)
07-14 01:35:46.250  3004  6444 W System.err:    at com.marianhello.bgloc.HttpPostService.postJSON(HttpPostService.java:38)
07-14 01:35:46.250  3004  6444 W System.err:    at com.marianhello.bgloc.LocationService$PostLocationTask.doInBackground(LocationService.java:306)
07-14 01:35:46.250  3004  6444 W System.err:    at com.marianhello.bgloc.LocationService$PostLocationTask.doInBackground(LocationService.java:290)
07-14 01:35:46.250  3004  6444 W System.err:    at android.os.AsyncTask$2.call(AsyncTask.java:287)
07-14 01:35:46.250  3004  6444 W System.err:    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
07-14 01:35:46.250  3004  6444 W System.err:    at java.util.concurrent.FutureTask.run(FutureTask.java:137)
07-14 01:35:46.250  3004  6444 W System.err:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
07-14 01:35:46.250  3004  6444 W System.err:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
07-14 01:35:46.250  3004  6444 W System.err:    at java.lang.Thread.run(Thread.java:856)
07-14 01:35:46.250  3004  6444 W System.err: Caused by: libcore.io.ErrnoException: sendto failed: ECONNRESET (Connection reset by peer)
07-14 01:35:46.250  3004  6444 W System.err:    at libcore.io.Posix.sendtoBytes(Native Method)
07-14 01:35:46.250  3004  6444 W System.err:    at libcore.io.Posix.sendto(Posix.java:146)
07-14 01:35:46.250  3004  6444 W System.err:    at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:177)
07-14 01:35:46.250  3004  6444 W System.err:    at libcore.io.IoBridge.sendto(IoBridge.java:473)
07-14 01:35:46.250  3004  6444 W System.err:    ... 17 more
07-14 01:35:46.270  3004  6444 D SQLiteLocationDAO: After insert, rowId = 2
07-14 01:35:46.270  3004  6444 D LocationService: Persisted Location: com.marianhello.bgloc.data.BackgroundLocation@43062940
```

**Comment by shyamal890** [comment]
Perusing through stackoverflow questions shows that `ECONNRESET (Connection reset by peer)` may be due to keeping http connections alive. In such cases android keeps the connection alive, while server may have closed it long time back triggering the error.

**Comment by mauron85** [comment]
If so, where is the problem? Plugin should create new connection if server closed previous.

**Comment by shyamal890** [comment]
I think you didn't understand the issue. 

Once a location is posted to the server android doesn't close the connection. When another location update is received, plugin tries to use the same old connection which has been long closed by the server - FAILS to upload location > stores in local storage. Have a look at the error above

**Comment by mauron85** [comment]
How can I reproduce this? Any server implementation that is doing that?

**Comment by mauron85** [comment]
Or can you try to reproduce with minimal server implementation?
```
var express    = require('express');
var bodyParser = require('body-parser');

var app = express();

// parse application/json
app.use(bodyParser.json({ type : '*/*' })); // force json

app.post('/path', function(request, response){
    console.log('Headers:\n', request.headers);
    console.log('Body:\n', request.body);
    console.log('------------------------------');
    response.sendStatus(200);
});

app.listen(3000);
console.log('Server started...');
```

**Comment by shyamal890** [comment]
I don't think there is an issue on the server side. Client needs to re-initiate connection for each location post, not happening it seems. Here is an stackoverflow issue that sheds more light.

http://stackoverflow.com/questions/11207394/getting-socketexception-connection-reset-by-peer-in-android

**Comment by mauron85** [comment]
>ok, the answer was that it's the server's fault 

as accepted answer

**Comment by mauron85** [comment]
And another one http://stackoverflow.com/questions/24021685/android-econnreset-on-http-connection

>The ECONNRESET (Connection reset by peer) generally means a server error/failure processing the request (Post in your case) . Can you debug/log the server side?

**Comment by shyamal890** [comment]
There is no error on server side with ELMAH logging enabled. Can you try adding 

`conn.setRequestProperty("connection", "close");
`This will disable "keep-alive" property which is on by default.

OR

`System.setProperty("http.keepAlive", "false");`

**Comment by mauron85** [comment]
No I'm not going to disable keepAlive, when I cannot reproduce issue. But you can fork and add it yourself.
