### ISSUE TITLE
Failed to install plugin

### ISSUE THREAD

**Issue by zulhfreelancer** [mauron85/cordova-plugin-background-geolocation#131]
I get this error:

```
ᐅ cordova plugin add cordova-plugin-mauron85-background-geolocation
Fetching plugin "cordova-plugin-mauron85-background-geolocation" via npm
Installing "cordova-plugin-mauron85-background-geolocation" for android
 Using this version of Cordova with older version of cordova-android is being deprecated. Consider upgrading to cordova-android@5.0.0 or newer.
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-mauron85-background-geolocation':TypeError: Uh oh!
Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1148:7)
    at module.exports.framework.install (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:142:35)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/platforms/PlatformApiPoly.js:660:27
    at Object.ActionStack.process (/usr/local/lib/node_modules/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PlatformApiPoly.addPlugin (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/platforms/PlatformApiPoly.js:255:20)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:611:6)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:407:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
Error: Uh oh!
Path must be a string. Received undefined
```

What should I do?

**Comment by jeffmarshall** [comment]
I'm having this problem too

**Comment by mauron85** [comment]
Post output of `cordova platform version android`

**Comment by srsarcasmo** [comment]
COULD NOT INSTALL THE PLUG-IN Telerik SHOW ME TO INSTALL ERROR
