### ISSUE TITLE
Conflict with phonegap-facebook-plugin building Android

### ISSUE THREAD

**Issue by francorest** [mauron85/cordova-plugin-background-geolocation#14]
Hi,
I'm developing an application in Ionic. The project includes Background Geolocation and Facebook plugins, and work great on iOS, but on Android can not be compiled together (successfully compiled if only one of the plugins is installed).
Apparently there is a problem with duplication of dependencies. The specific error is "Multiple files defined dex". After searching for solutions I read that Facebook plugin use android-support-v4, and quite possibly generates conflicts with some dependence on this project.

Here's my build error.
```
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)
```
Can you think of any solution to this problem?

Thanks

**Comment by mauron85** [comment]
Maybe you can try fork this repo and remove 

```
<framework src="com.google.android.gms:play-services-location:+" />
```

from ```plugin.xml```

**Comment by mauron85** [comment]
There is section in phonegap-plugin-push about this.
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md

Multidex

If you have an issue compiling the app and you're getting an error similar to this (com.android.dex.DexException: Multiple dex files define):

UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
    at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
    at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
    at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
    at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
    at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
    at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
    at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
    at com.android.dx.command.dexer.Main.run(Main.java:277)
    at com.android.dx.command.dexer.Main.main(Main.java:245)
    at com.android.dx.command.Main.main(Main.java:106)
Then at least one other plugin you have installed is using an outdated way to declare dependencies such as android-support or play-services-gcm. This causes gradle to fail, and you'll need to identify which plugin is causing it and request an update to the plugin author, so that it uses the proper way to declare dependencies for cordova. See this for the reference on the cordova plugin specification, it'll be usefull to mention it when creating an issue or requesting that plugin to be updated.

Common plugins to suffer from this outdated dependency management are plugins related to facebook, google+, notifications, crosswalk and google maps.

**Comment by mauron85** [comment]
Added notion into README.md how to resolve [multidex issues](https://github.com/mauron85/cordova-plugin-background-geolocation#multidex) specially facebook plugin. Closing
