### ISSUE TITLE
Android crash: REQUEST_PERMISSIONS null pointer

### ISSUE THREAD

**Issue by kristfal** [mauron85/cordova-plugin-background-geolocation#242]
A few devices are crashing in the wild with `version 2.2.4`.

## Your Environment
* Plugin version: 2.2.4
* Platform: Android
* OS version: 6.0.1 (so far only 6.0.1 devices)
* Device manufacturer and model: Sansung and Asus devices

## Stacktrace:

```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=0, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.isea.Embark/com.isea.Embark.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.error(org.json.JSONObject)' on a null object reference
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3699)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)
       at android.app.ActivityThread.-wrap16(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.error(org.json.JSONObject)' on a null object reference
       at com.tenforwardconsulting.cordova.BackgroundGeolocationPlugin.onRequestPermissionResult(BackgroundGeolocationPlugin.java:677)
       at org.apache.cordova.CordovaInterfaceImpl.onRequestPermissionResult(CordovaInterfaceImpl.java:213)
       at org.apache.cordova.CordovaActivity.onRequestPermissionsResult(CordovaActivity.java:498)
       at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:6582)
       at android.app.Activity.dispatchActivityResult(Activity.java:6460)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)
       at android.app.ActivityThread.-wrap16(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

This is happening on devices in the wild, so I can't get much more info besides the Crashlytics stack. Let me know if there is something else I can help with.

**Comment by gustavo-iniguez-goya** [comment]
Hi kristfal,

I saw this problem as well, but at a different line of code (BackgroundGeolocationPlugin.java:685):

>      java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=0, result=-1, data=Intent { >act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity >{com.neveralone/com.neveralone.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual >method 'void org.apache.cordova.CallbackContext.success()' on a null object reference
>                 Caused by: java.lang.NullPointerException: 
>                 Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.success()' on a >null object reference
>                 12-08 00:16:46.738 30968 30968 E AndroidRuntime:     
>                 at >com.tenforwardconsulting.cordova.BackgroundGeolocationPlugin.onRequestPermissionResult(BackgroundGeolocationPlugin.java:685)

I have no idea why this can happen. I just applied a workaround to see if the callback object was null:
> if (actionStartCallbackContext != null){
>     actionStartCallbackContext.error(JSONErrorFactory.getJSONError(PERMISSION_DENIED_ERROR_CODE, "Permission denied by user"));
> }
> if (actionStartCallbackContext != null){
>     actionStartCallbackContext.success();
> }

at least it hasn't crashed since then. If I find a good solution I'll post a PR.

cheers.

**Comment by shyamal890** [comment]
@mauron85 Hope, you know about this issue. Much needed fix

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
