### ISSUE TITLE
ionic 2.3.0 cordova_not_available error

### ISSUE THREAD

**Issue by gchokeen** [mauron85/cordova-plugin-background-geolocation#280]
I created new project with ionic 2.3.0 and tried implementing the geolocation background as said in [ionic 2 documentation](https://ionicframework.com/docs/v2/native/background-geolocation/). But when I tried access the code in chrome, I am getting cordova_not_available error. 

## Your Environment
* Plugin version: 2.2.5
* Platform: Android
* OS version: Ubuntu 14.04 LTS
* Device manufacturer and model:
* Cordova version (`cordova -v`): 6.5.0
* Cordova platform version (`cordova platform ls`):
* Plugin configuration options: 
* Link to your project:

## Context

> Ionic info
> 
> 
> Cordova CLI: 6.5.0 
> Ionic Framework Version: 2.3.0
> Ionic CLI Version: 2.2.1
> Ionic App Lib Version: 2.2.0
> Ionic App Scripts Version: 1.1.4
> ios-deploy version: Not installed
> ios-sim version: Not installed
> OS: Linux 3.13
> Node Version: v6.6.0
> Xcode version: Not installed
> 

## Debug logs
```
Error: Error in ./HomePage class HomePage - inline template:14:0 caused by: cordova_not_available
    at new Error (native)
    at Error.v (http://localhost:8100/build/polyfills.js:3:4864)
    at ViewWrappedError.BaseError [as constructor] (http://localhost:8100/build/main.js:36370:27)
    at ViewWrappedError.WrappedError [as constructor] (http://localhost:8100/build/main.js:36430:16)
    at new ViewWrappedError (http://localhost:8100/build/main.js:77612:16)
    at DebugAppView._rethrowWithContext (http://localhost:8100/build/main.js:133307:23)
    at DebugAppView.<anonymous> (http://localhost:8100/build/main.js:133324:23)
    at HTMLElement.<anonymous> (http://localhost:8100/build/main.js:57680:53)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:10284)
    at Object.onInvokeTask (http://localhost:8100/build/main.js:38018:37)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:10220)
    at e.runTask (http://localhost:8100/build/polyfills.js:3:7637)
    at HTMLElement.invoke (http://localhost:8100/build/polyfills.js:3:11397)
```

I think issue is caused because this plugin is not updated for while. So it's not compatible to https://learnionic2.com/2017/03/24/whats-new-ionic-2-3-0-update/

**Comment by Tyler-Darby** [comment]
You're getting the error because Cordova _isn't_ available. 

Cordova only loads on device. You need to add a check that cordova is loaded to run that code.

```if (this.platform.is('cordova')) { code } ```

**Comment by gchokeen** [comment]
Thanks for the tips, but all other plugins handles this infernally. Example camera plugin

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
