### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by gchokeen** [mauron85/cordova-plugin-background-geolocation#302]
## Your Environment

> Cordova CLI: 6.5.0 
> Ionic Framework Version: 3.2.1
> Ionic CLI Version: 2.2.1
> Ionic App Lib Version: 2.2.0
> Ionic App Scripts Version: 1.3.7
> ios-deploy version: Not installed
> ios-sim version: Not installed
> OS: Linux 3.13
> Node Version: v6.6.0
> Xcode version: Not installed
> 

## Context

Background service is not starting 

## Debug logs
```
HomePage.html:16 ERROR TypeError: Cannot read property 'split' of undefined
    at file:///android_asset/www/build/main.js:41923:75
    at Array.forEach (native)
    at file:///android_asset/www/build/main.js:41923:20
    at Map.forEach (native)
    at Headers.toJSON (file:///android_asset/www/build/main.js:41921:23)
    at JSON.stringify (<anonymous>)
    at androidExec (file:///android_asset/www/cordova.js:962:25)
    at Object.configure (file:///android_asset/www/plugins/cordova-plugin-mauron85-background-geolocation/www/backgroundGeolocation.js:39:9)
    at callCordovaPlugin (file:///android_asset/www/build/main.js:66865:43)
    at Observable._subscribe (file:///android_asset/www/build/main.js:66907:28)

```

##My plugin code
```
	startTracking(vehicleId) {
	 
	  // Background Tracking

		const config: BackgroundGeolocationConfig = {
						locationProvider:1,
			            desiredAccuracy: 10,
			            stationaryRadius: 10,
			            distanceFilter: 10,
			            interval:20000,
			            fastestInterval:20000,
			            activitiesInterval:10000,
			            debug: true, //  enable this hear sounds for background-geolocation life-cycle.
			            stopOnTerminate: false, // enable this to clear background location settings when the app terminates
					 	url: API_URL+'vehicles/'+vehicleId+'/location',
					    httpHeaders: this.auth.getHeaders(),
					    syncUrl:API_URL+'vehicles/'+vehicleId+'/location',																																																			
					    maxLocations: 200,	 
					    notificationTitle: 'CarPool Tracking',
					    notificationText: 'Enabled',
					    notificationIconColor: '#FEDD1E'		               
			    };

			this.backgroundGeolocation.configure(config)
			  .subscribe((location: BackgroundGeolocationResponse) => {

		    	this.backgroundGeolocation.finish(); // FOR IOS ONLY

		  	});

		  // Background Tracking

		  	this.backgroundGeolocation.start();	
	}
```

**Comment by mauron85** [comment]
I guess this ionic related. As in original plugin there is split method defined. Line #39 is https://github.com/mauron85/cordova-plugin-background-geolocation/blob/master/www/backgroundGeolocation.js#L25

**Comment by mauron85** [comment]
What version of plugin are you using. And where from it was installed. Was it npm - https://www.npmjs.com/package/cordova-plugin-mauron85-background-geolocation ?

**Comment by gchokeen** [comment]
I am using 2.2.5

**cordova-plugin-mauron85-background-geolocation 2.2.5 "CDVBackgroundGeolocation"**

I installed like this
```
$ ionic  plugin add cordova-plugin-mauron85-background-geolocation
$ npm install --save @ionic-native/background-geolocation
```

**Comment by mauron85** [comment]
Ok. I guess the error is from here https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/background-geolocation/index.ts#L372. In other words from ionic wrapper of this plugin. Not sure if I can help.

**Comment by mauron85** [comment]
Also try remove `httpHeaders: this.auth.getHeaders()` from your configure. As this is black box for me and might be cause of your issue too. And pls report.

**Comment by gchokeen** [comment]
Hi,

I attached content   from file:///android_asset/www/build/main.js related to this plugin

[bg-gelocation-file.txt](https://github.com/mauron85/cordova-plugin-background-geolocation/files/1087355/bg-gelocation-file.txt)


I will test about httpHeaders and let you know. Anyhow My headers are like below
```

     this.contentHeaders = new Headers();
     this.contentHeaders.set('Accept', 'application/json');
     this.contentHeaders.set('Content-Type', 'application/json');
```

**Comment by mauron85** [comment]
The fragment you attached is useless for debugging, it doesn't have original line numbers. And relevant part is also missing. Anyway my guest would be you're configuring with invalid http headers. If not, post fragment with lines preserved, so I can take look on these line:

line 41921: Headers.toJSON (file:///android_asset/www/build/main.js:41921:23)
line 41923: file:///android_asset/www/build/main.js:41923:75
line:66865:  at callCordovaPlugin (file:///android_asset/www/build/main.js:66865:43)
line:66907: at Observable._subscribe (file:///android_asset/www/build/main.js:66907:28)

**Comment by gchokeen** [comment]
```
  Headers.prototype.toJSON = function () {
        var _this = this;
        var /** @type {?} */ serialized = {};
        this._headers.forEach(function (values, name) {
            var /** @type {?} */ split = [];
            values.forEach(function (v) { return split.push.apply(split, v.split(',')); });
            serialized[((_this._normalizedNames.get(name)))] = split;
        });
        return serialized;
    };
```
```

function callCordovaPlugin(pluginObj, methodName, args, opts, resolve, reject) {
    if (opts === void 0) { opts = {}; }
    // Try to figure out where the success/error callbacks need to be bound
    // to our promise resolve/reject handlers.
    args = setIndex(args, opts, resolve, reject);
    var availabilityCheck = checkAvailability(pluginObj, methodName);
    if (availabilityCheck === true) {
        var pluginInstance = __webpack_require__.i(__WEBPACK_IMPORTED_MODULE_0__util__["b" /* getPlugin */])(pluginObj.constructor.getPluginRef());
        return pluginInstance[methodName].apply(pluginInstance, args);
    }
    else {
        return availabilityCheck;
    }
}
```
```


function wrapObservable(pluginObj, methodName, args, opts) {
    if (opts === void 0) { opts = {}; }
    return new __WEBPACK_IMPORTED_MODULE_2_rxjs_Observable__["Observable"](function (observer) {
        var pluginResult = callCordovaPlugin(pluginObj, methodName, args, opts, observer.next.bind(observer), observer.error.bind(observer));
        if (pluginResult && pluginResult.error) {
            observer.error(pluginResult.error);
            observer.complete();
        }
        return function () {
            try {
                if (opts.clearFunction) {
                    if (opts.clearWithArgs) {
                        return callCordovaPlugin(pluginObj, opts.clearFunction, args, opts, observer.next.bind(observer), observer.error.bind(observer));
                    }
                    return __webpack_require__.i(__WEBPACK_IMPORTED_MODULE_0__util__["e" /* get */])(window, pluginObj.constructor.getPluginRef())[opts.clearFunction].call(pluginObj, pluginResult);
                }
            }
            catch (e) {
                console.warn('Unable to clear the previous observable watch for', pluginObj.constructor.getPluginName(), methodName);
                console.error(e);
            }
        };
    });
}
```

**Comment by gchokeen** [comment]
It worked after commenting the httpHeaders

**Comment by gchokeen** [comment]
@mauron85 : Did you find a way to expose this option to [get status of background process](https://github.com/mauron85/cordova-plugin-background-geolocation/issues/228). I am using this plugin in 5 application. all the clients want this option. So it's really good if you able update this.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
