### ISSUE TITLE
App crash as I call the start method

### ISSUE THREAD

**Issue by Gurjit-ONEBCG** [mauron85/cordova-plugin-background-geolocation#429]
Plugin works fine till Oreo8.0
I update the device and SDK to 27 and I get this exception

  FATAL EXCEPTION: main
                                                                   Process: com.onebcg.devdci, PID: 21846
                                                                   android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=0 contentView=null vibrate=null sound=null smartAlertCount=0x0 defaults=0x0 flags=0x62 color=0x00000000 vis=PRIVATE)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                       at android.os.Looper.loop(Looper.java:164)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6501)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by mauron85** [comment]
What is the plugin version you're using?

**Comment by Gurjit-ONEBCG** [comment]
"cordova-plugin-mauron85-background-geolocation": "^2.3.5",

Gradle 4.4
Android-Cordova 7.1.0
IONIC 3

**Comment by Gurjit-ONEBCG** [comment]
any update pls

**Comment by mauron85** [comment]
Please next time avoid using: `Please provide the solution asap.`. I'm very sensitive on such pushy attempts. ;)

**Comment by Gurjit-ONEBCG** [comment]
ok waiting for update which can support android cordova 7.1.0

**Comment by Gurjit-ONEBCG** [comment]
ok waiting for the update which can support android cordova 7.1.0 and target sdk 27

**Comment by Gurjit-ONEBCG** [comment]
Thanks for the reply.
I tried to install
cordova plugin rm cordova-plugin-mauron85-background-geolocation@3.0.0
but it rejects this version
By default it installs the highest v 2.3.5
I am sorry to asking you this, can you please give me the direct command by which I can install the latest version of this plugin in my IONIC application (cordova android @7.1.0)
As here I see the max version
https://github.com/mauron85/cordova-plugin-background-geolocation/releases
2.3.5

**Comment by Gurjit-ONEBCG** [comment]
Tried by updating to the latest version of plugin 3.0.0-alpha.35
But it didn't work as expected
Issue- Does not work on app background and termination

**Comment by mauron85** [comment]
>Issue- Does not work on app background and termination

Please open new issue with all the details.

**Comment by Gurjit-ONEBCG** [comment]
Done  [#434](https://github.com/mauron85/cordova-plugin-background-geolocation/issues/434)
