### ISSUE TITLE
"dependencies.gradle" not found!

### ISSUE THREAD

**Issue by jld3103** [mauron85/cordova-plugin-background-geolocation#431]
## Your Environment

* Plugin version: Latest git version (as of 26.5 it's 3.0.0-alpha.34)
* Platform: Android
* Cordova version: 8.0.0
* Cordova platform version: android 7.1.0

## Context

I tried to add your plugin to my app, but if I add it it throws an error.

## Expected Behavior

The plugin should be added without errors.

## Actual Behavior

The plugin throws this error:
```
jld3103@bilbo:~/app$ cordova plugin add https://github.com/mauron85/cordova-plugin-ba
ckground-geolocation.git
Installing "cordova-plugin-mauron85-background-geolocation" for android
Android Studio project detected
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-mauron85-background-geolocation': CordovaError: Uh oh!
"app/plugins/cordova-plugin-mauron85-background-geolocation/android/dep
endencies.gradle" not found!
    at copyFile (app/platforms/android/cordova/lib/pluginHandlers.js:23
5:36)
    at copyNewFile (app/platforms/android/cordova/lib/pluginHandlers.js
:263:5)
    at install (app/platforms/android/cordova/lib/pluginHandlers.js:107:17)
    at ActionStack.process (app/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (app/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin (app/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
    at app/platforms/android/cordova/Api.js:247:74
    at _fulfilled (app/platforms/android/cordova/node_modules/q/q.js:854:54)
    at app/platforms/android/cordova/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (app/platforms/android/cordova/node_modules/q/q.js:816:13)
(node:7141) UnhandledPromiseRejectionWarning: CordovaError: Uh oh!
"app/plugins/cordova-plugin-mauron85-background-geolocation/android/dependencies.gradle" not found!
    at copyFile (app/platforms/android/cordova/lib/pluginHandlers.js:235:36)
    at copyNewFile (app/platforms/android/cordova/lib/pluginHandlers.js:263:5)
    at install (app/platforms/android/cordova/lib/pluginHandlers.js:107:17)
    at ActionStack.process (app/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (app/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin (app/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
    at app/platforms/android/cordova/Api.js:247:74
    at _fulfilled (app/platforms/android/cordova/node_modules/q/q.js:854:54)
    at app/platforms/android/cordova/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (app/platforms/android/cordova/node_modules/q/q.js:816:13)
(node:7141) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated eitherby throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7141) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Possible Fix

Add the dependencies.gradle file if it's missing (I think so).

**Comment by mauron85** [comment]
Did you installed from git or npm?

**Comment by mauron85** [comment]
Nevermind. You're right. it's missing from npmignore

**Comment by jld3103** [comment]
Do you mean cordova?

**Comment by jld3103** [comment]
Can you fix it soon?

**Comment by jld3103** [comment]
The you've missed the dependencies.gradle file
