### ISSUE TITLE
Android Oreo Issue

### ISSUE THREAD

**Issue by Maraket** [mauron85/cordova-plugin-background-geolocation#459]
## Your Environment

* Plugin version: 2.3.5
* Platform:  Android
* OS version: 8.1 Oreo (LineageOS build 15.1-20180609-UNOFFICIAL-m8)
* Device manufacturer and model: HTC M8
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): cordova platform ls
* Plugin configuration options: 
Using Ionic 3.9.2

```
{
      desiredAccuracy: 10,
      stationaryRadius: 20,
      distanceFilter: 10,
      interval: 30000,
      stopOnTerminate: false
    }
```
* Link to your project:

## Context

Using the background geolocation provider to track individual users, on Android Oreo

## Expected Behavior

On each call, my code runs

## Actual Behavior

Crashes the App

## Possible Fix

It appears the issue is to do specifically with Android Orea (SDK 27) as during debugging in Android Studio it is throwing:

```
android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x62 color=0x00000000 vis=PRIVATE)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

which is attached to https://stackoverflow.com/questions/47531742/startforeground-fail-after-upgrade-to-android-8-1 (albeit it is noted the code snippets are Kotlin and not java, though the principle is the same).

## Steps to Reproduce

1. Run basic example on Android 8.1
2.
3.
4.

## Debug logs

```
android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x62 color=0x00000000 vis=PRIVATE)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by joseiherq** [comment]
Same error! Do you find some fix? I tried the stackoverflow link, but i don't know where write the startForeground function...

**Comment by mauron85** [comment]
FYI Oreo support has been added in 3.x branch.

**Comment by joseiherq** [comment]
Thanks Mauron, problem resolved using 3.x branch on ionic!

**Comment by mauron85** [comment]
Glad to hear that. Closing this one.

**Comment by tupizz** [comment]
When i add in
