### ISSUE TITLE
Plugin crashes on android 23

### ISSUE THREAD

**Issue by uriva** [mauron85/cordova-plugin-background-geolocation#47]
It seems that there is something wrong with the runtime permissions request code. I'm getting this error:

```
03-02 21:49:15.448  2958  2958 E AndroidRuntime: FATAL EXCEPTION: main
03-02 21:49:15.448  2958  2958 E AndroidRuntime: Process: com.appspot.myapp:remote, PID: 2958
03-02 21:49:15.448  2958  2958 E AndroidRuntime: java.lang.RuntimeException: Unable to start service com.tenforwardconsulting.cordova.bgloc.DistanceFilterLocationService@68f8d93 with Intent { flg=0x4 cmp=com.appspot.myapp/com.tenforwardconsulting.cordova.bgloc.DistanceFilterLocationService (has extras) }: java.lang.SecurityException: "passive" location provider requires ACCESS_FINE_LOCATION permission.
03-02 21:49:15.448  2958  2958 E AndroidRuntime:        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3027)
03-02 21:49:15.448  2958  2958 E AndroidRuntime:        at android.app.ActivityThread.-wrap17(ActivityThread.java)
03-02 21:49:15.448  2958  2958 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1442)
03-02 21:49:15.448  2958  2958 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
03-02 21:49:15.448  2958  2958 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
03-02 21:49:15.448  2958  2958 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5417)
03-02 21:49:15.448  2958  2958 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-02 21:49:15.448  2958  2958 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-02 21:49:15.448  2958  2958 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
03-02 21:49:15.448  2958  2958 E AndroidRuntime: Caused by: java.lang.SecurityException: "passive" location provider requires ACCESS_FINE_LOCATION permission.
03-02 21:49:15.448  2958  2958 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1620)
03-02 21:49:15.448  2958  2958 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1573)
03-02 21:49:15.448  2958  2958 E AndroidRuntime:        at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:606)
03-02 21:49:15.448  2958  2958 E AndroidRuntime:        at android.location.LocationManager.requestLocationUpdates(LocationManager.java:880)
03-02 21:49:15.448  2958  2958 E AndroidRuntime:        at android.location.LocationManager.requestLocationUpdates(LocationManager.java:464)
03-02 21:49:15.448  2958  2958 E AndroidRuntime:        at com.tenforwardconsulting.cordova.bgloc.DistanceFilterLocationService.setPace(DistanceFilterLocationService.java:162)
03-02 21:49:15.448  2958  2958 E AndroidRuntime:        at com.tenforwardconsulting.cordova.bgloc.DistanceFilterLocationService.onStartCommand(DistanceFilterLocationService.java:113)
03-02 21:49:15.448  2958  2958 E AndroidRuntime:        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3010)
03-02 21:49:15.448  2958  2958 E AndroidRuntime:        ... 8 more

```

From looking at the code and comparing to https://cordova.apache.org/docs/en/dev/guide/platforms/android/plugin.html#runtime-permissions-cordova-android-5-0-0 perhaps we need to use `cordova.hasPermission`

**Comment by mauron85** [comment]
What version are you using? 0.9.4?

**Comment by uriva** [comment]
commit a2e37dc6167aa03622e8efbcb06ba8

**Comment by mauron85** [comment]
In fact there is PermissionHelper class that does permission check on plugin start (basically same thing as cordova.hasPermission). Do permission dialog show up, when you call start method?

**Comment by uriva** [comment]
It shows up but alongside with a crash.

**Comment by mauron85** [comment]
Ok. It's probably bug then. Can you post your plugin settings and how to reproduce? Thanks

**Comment by mauron85** [comment]
Any updates? Still crashing?

**Comment by mauron85** [comment]
please reopen, with more info

**Comment by Demayl** [comment]
Same here. It requires ACCESS_FINE_LOCATION permission for Android 6.0.
