### ISSUE TITLE
Exits unexpectedly when app gets terminated on android

### ISSUE THREAD

**Issue by dreadnautxbuddha** [mauron85/cordova-plugin-background-geolocation#489]
## Your Environment

* Plugin version: 2.3.6
* Platform: Android (haven't tried on iOS yet)
* OS version: 8.0.0
* Device manufacturer and model: Samsung Galaxy S9+
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): 
```
Installed platforms:
  android 7.1.1
  ios 4.5.5
Available platforms: 
  browser ~5.0.1
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0
```
* Plugin configuration options: 
```
    const config: BackgroundGeolocationConfig = {
      desiredAccuracy: 10,
      stationaryRadius: 20,
      distanceFilter: 30,
      debug: true,
      stopOnTerminate: true,
    };
```
* Link to your project: (private company project)

## Context

I'm new to mobile development and had a requirement for background geolocation. I copy-pasted the setup as described [here](https://ionicframework.com/docs/native/background-geolocation/#usage):

## Expected Behavior
It is working as expected. I'm getting location updates every now and then but with an additional log error: 
![screen shot 2018-10-01 at 8 57 04 am](https://user-images.githubusercontent.com/24476736/46265653-2c41b680-c55b-11e8-9a85-8513735e5961.png)

But still, i ignored this since i'm getting location updates. But having set `stopOnTerminate` to true, I was expecting that i can terminate the app gracefully.

## Actual Behavior
Upon closing the app, after about 2-3 seconds, I get an alert message saying that my app has stopped.

## Steps to Reproduce

1. Open the app
2. Wait for a few seconds
3. Close the app by swiping it away

## Context

I was hoping to have the app terminate without any errors.

## Debug logs

```
2018-10-01 08:42:18.263 4416-4416/? E/audit: type=1400 audit(1538354538.258:1135): avc:  denied  { read } for  pid=16651 comm="ne.fieldmagicv3" name="vmstat" dev="proc" ino=4026532577 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:proc:s0 tclass=file permissive=0 SEPF_SM-G965F_8.0.0_0014 audit_filtered
2018-10-01 08:42:18.263 4416-4416/? E/audit: type=1300 audit(1538354538.258:1135): arch=c00000b7 syscall=56 success=no exit=-13 a0=ffffff9c a1=7fd13d0059 a2=80000 a3=0 items=0 ppid=4950 pid=16651 auid=4294967295 uid=10309 gid=10309 euid=10309 suid=10309 fsuid=10309 egid=10309 sgid=10309 fsgid=10309 tty=(none) ses=4294967295 comm="ne.fieldmagicv3" exe="/system/bin/app_process64" subj=u:r:untrusted_app:s0:c512,c768 key=(null)
2018-10-01 08:42:18.263 4416-4416/? E/audit: type=1327 audit(1538354538.258:1135): proctitle="com.crmonline.fieldmagicv3"
2018-10-01 08:42:21.240 16651-16651/com.crmonline.fieldmagicv3 E/ViewRootImpl: sendUserActionEvent() returned.
2018-10-01 08:42:21.573 16651-16651/com.crmonline.fieldmagicv3 E/ViewRootImpl: sendUserActionEvent() returned.
2018-10-01 08:42:22.206 4820-4839/? E/NotificationService: No Channel found for pkg=com.crmonline.fieldmagicv3, channelId=null, id=1, tag=null, opPkg=com.crmonline.fieldmagicv3, callingUid=10309, userId=0, incomingUserId=0, notificationUid=10309, notification=Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x62 color=0x00000000 number=0 vis=PRIVATE semFlags=0x0 semPriority=0 semMissedCount=0)
2018-10-01 08:42:22.251 5556-5598/? E/RequestManager_FLP: [LocationManagerService] Location request d35603 passive interval=0 from com.crmonline.fieldmagicv3
2018-10-01 08:42:22.272 4820-6847/? E/PermissionMonitor: Calling app is not pre-installed on system. Ignore its notification. pkgName: com.crmonline.fieldmagicv3, UserId: 0
2018-10-01 08:42:22.296 5556-5598/? E/RequestManager_FLP: [LocationManagerService] Location request d35603 gps interval=0 from com.crmonline.fieldmagicv3
2018-10-01 08:42:22.301 4820-6472/? E/PermissionMonitor: Calling app is not pre-installed on system. Ignore its notification. pkgName: com.crmonline.fieldmagicv3, UserId: 0
2018-10-01 08:42:22.305 5556-5598/? E/RequestManager_FLP: [LocationManagerService] Location request d35603 network interval=0 from com.crmonline.fieldmagicv3
2018-10-01 08:42:22.308 4820-5461/? E/PermissionMonitor: Calling app is not pre-installed on system. Ignore its notification. pkgName: com.crmonline.fieldmagicv3, UserId: 0
2018-10-01 08:42:42.489 5556-5598/? E/RequestManager_FLP: [LocationManagerService] Location request a3d0ca fused interval=0 from com.crmonline.fieldmagicv3
2018-10-01 08:42:42.496 4820-5461/? E/PermissionMonitor: Calling app is not pre-installed on system. Ignore its notification. pkgName: com.crmonline.fieldmagicv3, UserId: 0
2018-10-01 08:42:42.532 5556-5598/? E/RequestManager_FLP: [LocationManagerService] Location remove a3d0ca from com.crmonline.fieldmagicv3
2018-10-01 08:42:42.633 5556-5598/? E/RequestManager_FLP: [LocationManagerService] Location remove d35603 from com.crmonline.fieldmagicv3
2018-10-01 08:42:42.639 5556-5598/? E/RequestManager_FLP: [LocationManagerService] Location request 8530f6 passive interval=0 from com.crmonline.fieldmagicv3
2018-10-01 08:42:42.644 4820-6472/? E/PermissionMonitor: Calling app is not pre-installed on system. Ignore its notification. pkgName: com.crmonline.fieldmagicv3, UserId: 0
2018-10-01 08:42:42.644 5556-5598/? E/RequestManager_FLP: [LocationManagerService] Location request 8530f6 gps interval=0 from com.crmonline.fieldmagicv3
2018-10-01 08:42:42.646 5556-5598/? E/RequestManager_FLP: [LocationManagerService] Location request 8530f6 network interval=0 from com.crmonline.fieldmagicv3
2018-10-01 08:42:42.652 4820-6472/? E/PermissionMonitor: Calling app is not pre-installed on system. Ignore its notification. pkgName: com.crmonline.fieldmagicv3, UserId: 0
2018-10-01 08:42:42.654 4820-6472/? E/PermissionMonitor: Calling app is not pre-installed on system. Ignore its notification. pkgName: com.crmonline.fieldmagicv3, UserId: 0
2018-10-01 08:42:44.386 5556-5598/? E/RequestManager_FLP: [LocationManagerService] Location remove 8530f6 from com.crmonline.fieldmagicv3
2018-10-01 08:42:44.397 5556-5598/? E/RequestManager_FLP: [LocationManagerService] Location request db442d7 network interval=10000 from com.crmonline.fieldmagicv3
2018-10-01 08:42:44.399 4820-6472/? E/PermissionMonitor: Calling app is not pre-installed on system. Ignore its notification. pkgName: com.crmonline.fieldmagicv3, UserId: 0
2018-10-01 08:43:52.108 4820-4839/? E/NotificationService: No Channel found for pkg=com.crmonline.fieldmagicv3, channelId=null, id=-574543954, tag=null, opPkg=com.crmonline.fieldmagicv3, callingUid=10309, userId=0, incomingUserId=0, notificationUid=10309, notification=Notification(channel=null pri=-2 contentView=null vibrate=null sound=null defaults=0x0 flags=0x42 color=0x00000000 number=0 vis=PRIVATE semFlags=0x0 semPriority=0 semMissedCount=0)
2018-10-01 08:43:53.980 5556-5598/? E/RequestManager_FLP: [LocationManagerService] Location remove db442d7 from com.crmonline.fieldmagicv3
2018-10-01 08:43:55.064 4820-4839/? E/NotificationService: No Channel found for pkg=com.crmonline.fieldmagicv3, channelId=null, id=1, tag=null, opPkg=com.crmonline.fieldmagicv3, callingUid=10309, userId=0, incomingUserId=0, notificationUid=10309, notification=Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x62 color=0x00000000 number=0 vis=PRIVATE semFlags=0x0 semPriority=0 semMissedCount=0)
2018-10-01 08:43:55.136 17669-17669/com.crmonline.fieldmagicv3 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.crmonline.fieldmagicv3, PID: 17669
    java.lang.RuntimeException: Unable to start service com.marianhello.bgloc.LocationService@8110c0b with Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.crmonline.fieldmagicv3/.MainActivity (has extras) }: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Boolean com.marianhello.bgloc.Config.getStopOnTerminate()' on a null object reference
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3694)
        at android.app.ActivityThread.-wrap21(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1801)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Boolean com.marianhello.bgloc.Config.getStopOnTerminate()' on a null object reference
        at com.marianhello.bgloc.LocationService.onTaskRemoved(LocationService.java:201)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3679)
        at android.app.ActivityThread.-wrap21(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1801) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6938) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 

```
Based on the logs, it was trying to restart background-geolocation but was unable since the app has been terminated already.

**Comment by dreadnautxbuddha** [comment]
This is the function i was running:
```
  private _watchDeviceLocationTest(): void {
    const config: BackgroundGeolocationConfig = {
      desiredAccuracy: 10,
      stationaryRadius: 20,
      distanceFilter: 30,
      debug: true, //  enable this hear sounds for background-geolocation life-cycle.
      stopOnTerminate: true, // enable this to clear background location settings when the app terminates
    };

    this._backgroundGeolocation.configure(config)
      .subscribe((location: BackgroundGeolocationResponse) => {

        console.log(location);

        // IMPORTANT:  You must execute the finish method here to inform the native plugin that you're finished,
        // and the background-task may be completed.  You must do this regardless if your HTTP request is successful or not.
        // IF YOU DON'T, ios will CRASH YOUR APP for spending too much time in the background.
        this._backgroundGeolocation.finish(); // FOR IOS ONLY

      });

    // start recording location
    this._backgroundGeolocation.start();
  }
```

I was not having any errors on app-close if i run 
`this._backgroundGeolocation.stop();`
but seeing that `stopOnTerminate` is set to true, i was expecting that i won't have to stop the process myself.

**Comment by dreadnautxbuddha** [comment]
I have tested the same scenario on two (2) other devices and listed below are the bug occurrences:

- [ ] Asus Zenfone 3 Max
- [x] Samsung Galaxy S8+

It seems that there is an issue with Samsung devices. It's also indicated [here.](https://github.com/mauron85/cordova-plugin-background-geolocation/issues/276#issuecomment-371877468)
So what would be the fix for this? Ionic Native seems to keep on installing v2.3.6 although v3.0.0 is already rolled out. I tried installing v3.0.0 manually but configuring it is a pain since Ionic's helpers aren't available. It would be great if you inform the Ionic team ASAP about this.

**Comment by dreadnautxbuddha** [comment]
@mauron85 any updates on this?

**Comment by mauron85** [comment]
Unfortunately I don't have resources to support 2.x anymore. Even though it's pain to use with ionic, I suggest you to try version 3.x.

**Comment by dreadnautxbuddha** [comment]
understood. But is there any way you can inform the Ionic team about this? They should update their Ionic Native library to use 3.x instead.

**Comment by mauron85** [comment]
I have no relations with Ionic whatsoever. However they might be reluctant to update, due 3.x being still in alpha.

**Comment by dreadnautxbuddha** [comment]
Is it nearing an official release?
