### ISSUE TITLE
Android P Error on 2.xx

### ISSUE THREAD

**Issue by rodrigoords** [mauron85/cordova-plugin-background-geolocation#493]
With 2.xx version when running on android P system crash with stacktrace:
android.app.RemoteServiceException: Bad notification for startForeground: 
```
java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x62 color=0x00000000 vis=PRIVATE)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1724)
                      at android.os.Handler.dispatchMessage(Handler.java:106)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6649)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)
E/UncaughtException: android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x62 color=0x00000000 vis=PRIVATE)
                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1724)
                         at android.os.Handler.dispatchMessage(Handler.java:106)
                         at android.os.Looper.loop(Looper.java:164)
                         at android.app.ActivityThread.main(ActivityThread.java:6649)
                         at java.lang.reflect.Method.invoke(Native Method)
                         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826) 
```

## Your Environment
* Ionic 3.xx project  
* Plugin version: 2.3.6
* Platform: Android
* OS version: P
* Device manufacturer and model: 
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): 7.1.0
* Plugin configuration options: 
* Link to your project:

**Comment by mauron85** [comment]
Thank you for raising this. But unfortunately 2.x will not working on Oreo
or later, due changes in notifications system. 3.x should be working fine.

**Comment by dreadnautxbuddha** [comment]
Hi @mauron85 , it would be better if the Ionic team gets informed about this

**Comment by mauron85** [comment]
Action needed in ionic side. Closing, as there is not much we can do here.
