### ISSUE TITLE
plugin not working in pie with google map navigator

### ISSUE THREAD

**Issue by RajanYugtia** [mauron85/cordova-plugin-background-geolocation#534]
Plugin not working with navigator in android pie.

## Your Environment
* Plugin version:3.0.0-alpha.50
* Platform: Android
* OS version: 9.0
* Device manufacturer and model: MI A2
* Running in Simulator:No (Pixel 9.0)
* Cordova version (7.1.0):
* Cordova platform version (6.3.0):
* Plugin configuration options: 
  desired accuracy : 10
  stationary radius : 20 
  distance filter : 30
  maxLocations : 10
  stopOnTerminate :false
* Link to your project:

## Context
This plugin is not working with my navigator plugin and crashing on android pie.

## Expected Behavior
This should work in my project.

## Actual Behavior
App is crashing and location plugin is going to undefined.

## Steps to Reproduce
1. Install app
2. App crashes
3. location.start becomes undefined.

## Context
I am doing project on urgency basis. Please help me asap.

## Debug logs
2019-01-04 15:40:23.364 30236-30236/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.#####.#########, PID: 30236
    android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=-2 contentView=null vibrate=null sound=null defaults=0x0 flags=0x42 color=0x00000000 vis=PRIVATE)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1737)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

and backgroundGeolocation.start throwing error "Undefined"

@mauron85  please help me asap.

**Comment by YoshiyukiKumagai** [comment]
Why did you closed?
I have the same problem.
If you solve the problem, please write that way.

**Comment by RajanYugtia** [comment]
There is no such issue with plugin.
