### ISSUE TITLE
Doesn't build when android-targetSdkVersion is 28

### ISSUE THREAD

**Issue by andersborgabiro** [mauron85/cordova-plugin-background-geolocation#547]
When building an app using this plugin it fails building when android-targetSdkVersion is 28.

## Your Environment
* Plugin version: 3.0.0-alpha.50
* Platform: Android
* OS version: 7
* Device manufacturer and model: Sony Xperia L1
* Cordova version (`cordova -v`): cli-8.0.0
* Cordova platform version (`cordova platform ls`): 7.0.0
* Plugin configuration options:
```
    <plugin name="cordova-plugin-mauron85-background-geolocation">
        <variable name="GOOGLE_PLAY_SERVICES_VERSION" value="11+" />
        <variable name="ANDROID_SUPPORT_LIBRARY_VERSION" value="23+" />
        <variable name="ALWAYS_USAGE_DESCRIPTION" value="The app needs background location tracking" />
        <variable name="MOTION_USAGE_DESCRIPTION" value="Accelerometer use increases battery efficiency by intelligently toggling location tracking" />
    </plugin>
```
## Context
Building using PhoneGap Build.

## Expected Behavior
Building without error.

## Actual Behavior
I get an error log when I build an app with this plugin included. The error goes away when the plugin is removed. Se below log file from PGB.

## Possible Fix
Removing this plugin (not a good solution :) )

## Steps to Reproduce
Set android-targetSdkVersion to 28
Include this plugin with the mentioned options
Build with PGB
Error log

## Context
The impact is low initially, but over time I need to support Android 9 as well.

## Debug logs

(note marianhello)

Build Date: 2019-02-01 11:13:48 +0000
--------------------------------------------------------------------------------
PREPARE OUTPUT
--------------------------------------------------------------------------------
Android Studio project detected
Generating platform-specific config.xml from defaults for android at /app/src/main/res/xml/config.xml
Merging project's config.xml into platform-specific android config.xml
Merging and updating files from [, ../platform_www] to ../app/src/main/assets/www
  copy  config.xml ../app/src/main/assets/www/config.xml (new file)
  mkdir ../app/src/main/assets/www/cordova-js-src
  mkdir ../app/src/main/assets/www/cordova-js-src/android
  copy  ../platform_www/cordova-js-src/android/nativeapiprovider.js ../app/src/main/assets/www/cordova-js-src/android/nativeapiprovider.js (new file)
  copy  ../platform_www/cordova-js-src/android/promptbasednativeapi.js ../app/src/main/assets/www/cordova-js-src/android/promptbasednativeapi.js (new file)
  copy  ../platform_www/cordova-js-src/exec.js ../app/src/main/assets/www/cordova-js-src/exec.js (new file)
  copy  ../platform_www/cordova-js-src/platform.js ../app/src/main/assets/www/cordova-js-src/platform.js (new file)
  mkdir ../app/src/main/assets/www/cordova-js-src/plugin
  mkdir ../app/src/main/assets/www/cordova-js-src/plugin/android
  copy  ../platform_www/cordova-js-src/plugin/android/app.js ../app/src/main/assets/www/cordova-js-src/plugin/android/app.js (new file)
  copy  ../platform_www/cordova.js ../app/src/main/assets/www/cordova.js (updated file)
  copy  css/index.css ../app/src/main/assets/www/css/index.css (updated file)
  mkdir ../app/src/main/assets/www/images
  copy  images/banner-dark.png ../app/src/main/assets/www/images/banner-dark.png (new file)
  copy  images/banner-light.png ../app/src/main/assets/www/images/banner-light.png (new file)
  copy  images/bluetooth.png ../app/src/main/assets/www/images/bluetooth.png (new file)
  copy  images/centerlogo-dark.png ../app/src/main/assets/www/images/centerlogo-dark.png (new file)
  copy  images/centerlogo-light.png ../app/src/main/assets/www/images/centerlogo-light.png (new file)
  copy  images/icon.png ../app/src/main/assets/www/images/icon.png (new file)
  copy  images/inside.png ../app/src/main/assets/www/images/inside.png (new file)
  copy  images/location.png ../app/src/main/assets/www/images/location.png (new file)
  copy  images/menu.png ../app/src/main/assets/www/images/menu.png (new file)
  copy  images/splash.png ../app/src/main/assets/www/images/splash.png (new file)
  copy  images/sync.png ../app/src/main/assets/www/images/sync.png (new file)
  rmdir  ../app/src/main/assets/www/img (no source)
  delete ../app/src/main/assets/www/img/cordova.png (no source)
  delete ../app/src/main/assets/www/img/logo.png (no source)
  copy  index.html ../app/src/main/assets/www/index.html (updated file)
  copy  js/autostart.js ../app/src/main/assets/www/js/autostart.js (new file)
  copy  js/backgroundmode.js ../app/src/main/assets/www/js/backgroundmode.js (new file)
  copy  js/badge.js ../app/src/main/assets/www/js/badge.js (new file)
  copy  js/barcode.js ../app/src/main/assets/www/js/barcode.js (new file)
  copy  js/beacon.js ../app/src/main/assets/www/js/beacon.js (new file)
  copy  js/browser.js ../app/src/main/assets/www/js/browser.js (new file)
  copy  js/config.js ../app/src/main/assets/www/js/config.js (new file)
  copy  js/dialogs.js ../app/src/main/assets/www/js/dialogs.js (new file)
  copy  js/geolocation.js ../app/src/main/assets/www/js/geolocation.js (new file)
  copy  js/html.js ../app/src/main/assets/www/js/html.js (new file)
  copy  js/index.js ../app/src/main/assets/www/js/index.js (updated file)
  copy  js/information.js ../app/src/main/assets/www/js/information.js (new file)
  copy  js/nav.js ../app/src/main/assets/www/js/nav.js (new file)
  copy  js/notification.js ../app/src/main/assets/www/js/notification.js (new file)
  copy  js/permissions.js ../app/src/main/assets/www/js/permissions.js (new file)
  copy  js/poke.js ../app/src/main/assets/www/js/poke.js (new file)
  copy  js/preferences.js ../app/src/main/assets/www/js/preferences.js (new file)
  copy  js/preferencesmgr.js ../app/src/main/assets/www/js/preferencesmgr.js (new file)
  copy  js/theme.js ../app/src/main/assets/www/js/theme.js (new file)
  copy  js/toast.js ../app/src/main/assets/www/js/toast.js (new file)
  copy  js/translations.js ../app/src/main/assets/www/js/translations.js (new file)
  copy  js/translationsmgr.js ../app/src/main/assets/www/js/translationsmgr.js (new file)
  copy  js/utils.js ../app/src/main/assets/www/js/utils.js (new file)
  copy  main.html ../app/src/main/assets/www/main.html (new file)
  mkdir ../app/src/main/assets/www/res
  copy  res/.pgbomit ../app/src/main/assets/www/res/.pgbomit (new file)
  mkdir ../app/src/main/assets/www/res/icon
  mkdir ../app/src/main/assets/www/res/icon/android
  copy  res/icon/android/hdpi.png ../app/src/main/assets/www/res/icon/android/hdpi.png (new file)
  copy  res/icon/android/ldpi.png ../app/src/main/assets/www/res/icon/android/ldpi.png (new file)
  copy  res/icon/android/mdpi.png ../app/src/main/assets/www/res/icon/android/mdpi.png (new file)
  copy  res/icon/android/xhdpi.png ../app/src/main/assets/www/res/icon/android/xhdpi.png (new file)
  copy  res/icon/android/xxhdpi.png ../app/src/main/assets/www/res/icon/android/xxhdpi.png (new file)
  copy  res/icon/android/xxxhdpi.png ../app/src/main/assets/www/res/icon/android/xxxhdpi.png (new file)
  mkdir ../app/src/main/assets/www/res/icon/ios
  copy  res/icon/ios/icon-1024.png ../app/src/main/assets/www/res/icon/ios/icon-1024.png (new file)
  copy  res/icon/ios/icon-167.png ../app/src/main/assets/www/res/icon/ios/icon-167.png (new file)
  copy  res/icon/ios/icon-60.png ../app/src/main/assets/www/res/icon/ios/icon-60.png (new file)
  copy  res/icon/ios/icon-60@2x.png ../app/src/main/assets/www/res/icon/ios/icon-60@2x.png (new file)
  copy  res/icon/ios/icon-60@3x.png ../app/src/main/assets/www/res/icon/ios/icon-60@3x.png (new file)
  copy  res/icon/ios/icon-72.png ../app/src/main/assets/www/res/icon/ios/icon-72.png (new file)
  copy  res/icon/ios/icon-72@2x.png ../app/src/main/assets/www/res/icon/ios/icon-72@2x.png (new file)
  copy  res/icon/ios/icon-76.png ../app/src/main/assets/www/res/icon/ios/icon-76.png (new file)
  copy  res/icon/ios/icon-76@2x.png ../app/src/main/assets/www/res/icon/ios/icon-76@2x.png (new file)
  copy  res/icon/ios/icon-83.5@2x.png ../app/src/main/assets/www/res/icon/ios/icon-83.5@2x.png (new file)
  copy  res/icon/ios/icon-small-40.png ../app/src/main/assets/www/res/icon/ios/icon-small-40.png (new file)
  copy  res/icon/ios/icon-small-40@2x.png ../app/src/main/assets/www/res/icon/ios/icon-small-40@2x.png (new file)
  copy  res/icon/ios/icon-small-40@3x.png ../app/src/main/assets/www/res/icon/ios/icon-small-40@3x.png (new file)
  copy  res/icon/ios/icon-small-50.png ../app/src/main/assets/www/res/icon/ios/icon-small-50.png (new file)
  copy  res/icon/ios/icon-small-50@2x.png ../app/src/main/assets/www/res/icon/ios/icon-small-50@2x.png (new file)
  copy  res/icon/ios/icon-small.png ../app/src/main/assets/www/res/icon/ios/icon-small.png (new file)
  copy  res/icon/ios/icon-small@2x.png ../app/src/main/assets/www/res/icon/ios/icon-small@2x.png (new file)
  copy  res/icon/ios/icon-small@3x.png ../app/src/main/assets/www/res/icon/ios/icon-small@3x.png (new file)
  copy  res/icon/ios/icon.png ../app/src/main/assets/www/res/icon/ios/icon.png (new file)
  copy  res/icon/ios/icon@2x.png ../app/src/main/assets/www/res/icon/ios/icon@2x.png (new file)
  mkdir ../app/src/main/assets/www/res/screen
  mkdir ../app/src/main/assets/www/res/screen/android
  copy  res/screen/android/splash-port-hdpi.png ../app/src/main/assets/www/res/screen/android/splash-port-hdpi.png (new file)
  copy  res/screen/android/splash-port-ldpi.png ../app/src/main/assets/www/res/screen/android/splash-port-ldpi.png (new file)
  copy  res/screen/android/splash-port-mdpi.png ../app/src/main/assets/www/res/screen/android/splash-port-mdpi.png (new file)
  copy  res/screen/android/splash-port-xhdpi.png ../app/src/main/assets/www/res/screen/android/splash-port-xhdpi.png (new file)
  copy  res/screen/android/splash-port-xxhdpi.png ../app/src/main/assets/www/res/screen/android/splash-port-xxhdpi.png (new file)
  copy  res/screen/android/splash-port-xxxhdpi.png ../app/src/main/assets/www/res/screen/android/splash-port-xxxhdpi.png (new file)
  mkdir ../app/src/main/assets/www/res/screen/ios
  copy  res/screen/ios/Default@2x~ipad~anyany.png ../app/src/main/assets/www/res/screen/ios/Default@2x~ipad~anyany.png (new file)
  copy  res/screen/ios/Default@2x~ipad~comany.png ../app/src/main/assets/www/res/screen/ios/Default@2x~ipad~comany.png (new file)
  copy  res/screen/ios/Default@2x~iphone~anyany.png ../app/src/main/assets/www/res/screen/ios/Default@2x~iphone~anyany.png (new file)
  copy  res/screen/ios/Default@2x~iphone~comany.png ../app/src/main/assets/www/res/screen/ios/Default@2x~iphone~comany.png (new file)
  copy  res/screen/ios/Default@3x~iphone~anyany.png ../app/src/main/assets/www/res/screen/ios/Default@3x~iphone~anyany.png (new file)
  copy  res/screen/ios/Default@3x~iphone~comany.png ../app/src/main/assets/www/res/screen/ios/Default@3x~iphone~comany.png (new file)
  copy  test.html ../app/src/main/assets/www/test.html (new file)
Wrote out android application name "CliqTags Spotter" to /app/src/main/res/values/strings.xml
Wrote out Android package name "com.abiro.cliqtagsspotter" to /app/src/main/java/com/abiro/cliqtagsspotter/CliqTagsSpotter.java
Updating icons at ../app/src/main/res
  copy  res/icon/android/hdpi.png ../app/src/main/res/mipmap-hdpi/icon.png (updated file)
  copy  res/icon/android/ldpi.png ../app/src/main/res/mipmap-ldpi/icon.png (updated file)
  copy  res/icon/android/mdpi.png ../app/src/main/res/mipmap-mdpi/icon.png (updated file)
  copy  res/icon/android/xhdpi.png ../app/src/main/res/mipmap-xhdpi/icon.png (updated file)
  copy  res/icon/android/xxhdpi.png ../app/src/main/res/mipmap-xxhdpi/icon.png (updated file)
  copy  res/icon/android/xxxhdpi.png ../app/src/main/res/mipmap-xxxhdpi/icon.png (updated file)
Updating splash screens at ../app/src/main/res
  delete ../app/src/main/res/drawable-land-hdpi/screen.png (no source)
  delete ../app/src/main/res/drawable-land-ldpi/screen.png (no source)
  delete ../app/src/main/res/drawable-land-mdpi/screen.png (no source)
  delete ../app/src/main/res/drawable-land-xhdpi/screen.png (no source)
  delete ../app/src/main/res/drawable-land-xxhdpi/screen.png (no source)
  delete ../app/src/main/res/drawable-land-xxxhdpi/screen.png (no source)
  copy  images/splash.png ../app/src/main/res/drawable-mdpi/screen.png (new file)
  copy  res/screen/android/splash-port-hdpi.png ../app/src/main/res/drawable-port-hdpi/screen.png (updated file)
  copy  res/screen/android/splash-port-ldpi.png ../app/src/main/res/drawable-port-ldpi/screen.png (updated file)
  copy  res/screen/android/splash-port-mdpi.png ../app/src/main/res/drawable-port-mdpi/screen.png (updated file)
  copy  res/screen/android/splash-port-xhdpi.png ../app/src/main/res/drawable-port-xhdpi/screen.png (updated file)
  copy  res/screen/android/splash-port-xxhdpi.png ../app/src/main/res/drawable-port-xxhdpi/screen.png (updated file)
  copy  res/screen/android/splash-port-xxxhdpi.png ../app/src/main/res/drawable-port-xxxhdpi/screen.png (updated file)
This app does not have additional resource files defined
Prepared android project successfully
--------------------------------------------------------------------------------
PLUGIN OUTPUT
--------------------------------------------------------------------------------
Fetching plugin "cordova-plugin-whitelist" via npm
Installing "cordova-plugin-whitelist" at "1.3.3" for android
Android Studio project detected

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
Fetching plugin "cordova-plugin-device" via npm
Installing "cordova-plugin-device" at "2.0.2" for android
Android Studio project detected
Fetching plugin "cordova-plugin-inappbrowser" via npm
Installing "cordova-plugin-inappbrowser" at "3.0.0" for android
Android Studio project detected
Fetching plugin "cordova-plugin-statusbar" via npm
Installing "cordova-plugin-statusbar" at "2.4.2" for android
Android Studio project detected
Fetching plugin "cordova-plugin-dialogs" via npm
Installing "cordova-plugin-dialogs" at "2.0.1" for android
Android Studio project detected
Fetching plugin "cordova-plugin-appversion" via npm
Installing "cordova-plugin-appversion" at "1.0.0" for android
Android Studio project detected
Fetching plugin "cordova-plugin-x-toast" via npm
Installing "cordova-plugin-x-toast" at "2.7.2" for android
Android Studio project detected
Fetching plugin "cordova-plugin-network-information" via npm
Installing "cordova-plugin-network-information" at "2.0.1" for android
Android Studio project detected
Fetching plugin "cordova-plugin-globalization" via npm
Installing "cordova-plugin-globalization" at "1.11.0" for android
Android Studio project detected
Fetching plugin "cordova-plugin-vibration" via npm
Installing "cordova-plugin-vibration" at "3.1.0" for android
Android Studio project detected
Fetching plugin "cordova-plugin-splashscreen" via npm
Installing "cordova-plugin-splashscreen" at "5.0.2" for android
Android Studio project detected
Fetching plugin "https://github.com/Steffaan/cordova-plugin-local-notifications" via git clone
Using shallow clone
Repository "https://github.com/Steffaan/cordova-plugin-local-notifications" checked out to git ref "master" at "2b60660".
Installing "cordova-plugin-local-notification" at "0.9.2" for android
Plugin dependency "cordova-plugin-device@2.0.2" already fetched, using that version.
Dependent plugin "cordova-plugin-device" already installed on android.
Fetching plugin "cordova-plugin-badge@>=0.8.5" via npm
Installing "cordova-plugin-badge" at "0.8.8" for android
Android Studio project detected
Subproject Path: CordovaLib
Subproject Path: app
Subproject Path: CordovaLib
Subproject Path: app
Fetching plugin "cordova-plugin-autostart" via npm
Installing "cordova-plugin-autostart" at "2.3.0" for android
Android Studio project detected
Fetching plugin "com.unarin.cordova.beacon@3.7.0" via npm
Installing "com.unarin.cordova.beacon" at "3.7.0" for android
Plugin dependency "cordova-plugin-device@2.0.2" already fetched, using that version.
Dependent plugin "cordova-plugin-device" already installed on android.
Android Studio project detected
Subproject Path: CordovaLib
Subproject Path: app
Fetching plugin "cordova-plugin-geolocation" via npm
Installing "cordova-plugin-geolocation" at "4.0.1" for android
Android Studio project detected
Fetching plugin "cordova-plugin-background-mode" via npm
Installing "cordova-plugin-background-mode" at "0.7.2" for android
Plugin dependency "cordova-plugin-device@2.0.2" already fetched, using that version.
Dependent plugin "cordova-plugin-device" already installed on android.
Android Studio project detected
Fetching plugin "phonegap-plugin-barcodescanner" via npm
Installing "phonegap-plugin-barcodescanner" at "8.0.1" for android
Android Studio project detected
Subproject Path: CordovaLib
Subproject Path: app
Fetching plugin "cordova-plugin-android-permissions" via npm
Installing "cordova-plugin-android-permissions" at "1.0.0" for android
Android Studio project detected
Plugin "cordova-plugin-badge" already installed on android. Making it top-level.
Fetching plugin "cordova-plugin-ios-ble-permissions" via npm
Installing "cordova-plugin-ios-ble-permissions" at "1.0.3" for android
Android Studio project detected
Fetching plugin "cordova-plugin-customurlscheme" via npm
Installing "cordova-plugin-customurlscheme" at "4.3.0" for android
Android Studio project detected
Fetching plugin "cordova-custom-config" via npm
Installing "cordova-custom-config" at "5.0.3" for android
Android Studio project detected
Fetching plugin "cordova-plugin-mauron85-background-geolocation" via npm
Installing "cordova-plugin-mauron85-background-geolocation" at "3.0.0-alpha.50" for android
Android Studio project detected
Subproject Path: CordovaLib
Subproject Path: app
Fetching plugin "cordova-android-support-gradle-release" via npm
Installing "cordova-android-support-gradle-release" at "2.0.1" for android
Android Studio project detected
Subproject Path: CordovaLib
Subproject Path: app
Android Studio project detected
WARNING: Overriding compileSdkVersion from android-26 (default) to android-28
WARNING: This is unsupported, please consider updating your phonegap version instead
--------------------------------------------------------------------------------
PROJECT PROPERTIES
--------------------------------------------------------------------------------
# This file was originally created by the Android Tools, but is now
# used by cordova-android to manage the state of the various third party
# libraries used in your application

# This is the Library Module that contains the Cordova Library, this is not
# required when using an AAR

# This is the application project.  This is only required for Android Studio Gradle projects

# Project target.
target=android-28
android.library.reference.1=CordovaLib
android.library.reference.2=app
cordova.gradle.include.1=cordova-plugin-badge/cliqtagsspotter-badge.gradle
cordova.system.library.1=com.android.support:support-v4:26.+
cordova.gradle.include.2=cordova-plugin-local-notification/cliqtagsspotter-localnotification.gradle
cordova.gradle.include.3=com.unarin.cordova.beacon/cliqtagsspotter-cordova-plugin-ibeacon.gradle
cordova.system.library.2=com.android.support:support-core-utils:26+
cordova.gradle.include.4=phonegap-plugin-barcodescanner/cliqtagsspotter-barcodescanner.gradle
cordova.system.library.3=com.android.support:support-v4:27.+
cordova.system.library.4=com.google.android.gms:play-services-location:11+
cordova.system.library.5=com.android.support:support-v4:23+
cordova.system.library.6=com.android.support:appcompat-v7:23+
cordova.gradle.include.5=cordova-plugin-mauron85-background-geolocation/cliqtagsspotter-dependencies.gradle
cordova.gradle.include.6=cordova-android-support-gradle-release/cliqtagsspotter-cordova-android-support-gradle-release.gradle
--------------------------------------------------------------------------------
COMPILE OUTPUT
--------------------------------------------------------------------------------
Android Studio project detected
studio
:wrapper

BUILD SUCCESSFUL in 2s
1 actionable task: 1 executed
Subproject Path: CordovaLib
Subproject Path: app
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/4.1/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing
publishNonDefault is deprecated and has no effect anymore. All variants are now published.
Exception while marshalling /opt/android-sdk/build-tools/26.0.3/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/extras/google/instantapps/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/platform-tools/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/platforms/android-28/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/26.0.3/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/extras/google/instantapps/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/platform-tools/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/platforms/android-28/package.xml. Probably the SDK is read-only
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
+-----------------------------------------------------------------
| cordova-android-support-gradle-release: 27.+
+-----------------------------------------------------------------
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
	at build_bggtdx96qx6uuoq2qunollv6j.run(/app/build.gradle:149)
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:compileDebugAidl
:CordovaLib:compileDebugRenderscript
:CordovaLib:checkDebugManifest
:CordovaLib:generateDebugBuildConfig
:CordovaLib:prepareLintJar
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:platformAttrExtractor
:CordovaLib:processDebugManifest
:CordovaLib:javaPreCompileDebug
:CordovaLib:processDebugJavaRes NO-SOURCE
:app:preBuild UP-TO-DATE
:app:preDebugBuild
Download https://repo1.maven.org/maven2/com/github/tony19/logback-android/1.1.1-9/logback-android-1.1.1-9.pom
Download https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.21/slf4j-api-1.7.21.pom
Download https://repo1.maven.org/maven2/me/leolin/ShortcutBadger/1.1.22/ShortcutBadger-1.1.22.pom
Download https://repo1.maven.org/maven2/org/slf4j/slf4j-parent/1.7.21/slf4j-parent-1.7.21.pom
Download https://repo1.maven.org/maven2/com/github/jparkie/promise/1.0.3/promise-1.0.3.pom
Download https://jcenter.bintray.com/org/altbeacon/android-beacon-library/2.14/android-beacon-library-2.14.pom
Download https://jcenter.bintray.com/com/intentfilter/android-permissions/0.1.7/android-permissions-0.1.7.pom
Download https://repo1.maven.org/maven2/com/github/tony19/apktool-lib/1.4.4-5/apktool-lib-1.4.4-5.pom
Download https://maven.google.com/com/android/support/support-vector-drawable/maven-metadata.xml
Download https://maven.google.com/com/android/support/animated-vector-drawable/maven-metadata.xml
Download https://repo1.maven.org/maven2/me/leolin/ShortcutBadger/1.1.22/ShortcutBadger-1.1.22.aar
Download https://repo1.maven.org/maven2/com/github/tony19/logback-android/1.1.1-9/logback-android-1.1.1-9.aar
Download https://repo1.maven.org/maven2/com/github/tony19/apktool-lib/1.4.4-5/apktool-lib-1.4.4-5.aar
Download https://jcenter.bintray.com/org/altbeacon/android-beacon-library/2.14/android-beacon-library-2.14.aar
Download https://jcenter.bintray.com/com/intentfilter/android-permissions/0.1.7/android-permissions-0.1.7.aar
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:compileDebugJavaWithJavacNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug
:app:compileDebugAidl
:CordovaLib:packageDebugRenderscript NO-SOURCE
:app:compileDebugRenderscript
:app:checkDebugManifest
:app:generateDebugBuildConfig
:app:prepareLintJar
:app:generateDebugResValues
:app:generateDebugResources
:app:mergeDebugResources
:app:createDebugCompatibleScreenManifests
:app:processDebugManifest
:app:splitsDiscoveryTaskDebug
:app:processDebugResources
:app:generateDebugSources
:app:javaPreCompileDebug
Download https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.21/slf4j-api-1.7.21.jar
Download https://repo1.maven.org/maven2/com/github/jparkie/promise/1.0.3/promise-1.0.3.jar
:app:compileDebugJavaWithJavac/app/src/main/java/com/marianhello/bgloc/service/LocationServiceIntentBuilder.java:26: error: package junit.framework does not exist
import junit.framework.Assert;
                      ^
/app/src/main/java/com/marianhello/bgloc/service/LocationServiceIntentBuilder.java:164: error: cannot find symbol
        Assert.assertNotNull("Context can not be null!", mContext);
        ^
  symbol:   variable Assert
  location: class LocationServiceIntentBuilder
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s
27 actionable tasks: 27 executed
Error: /gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/app/src/main/java/com/marianhello/bgloc/service/LocationServiceIntentBuilder.java:26: error: package junit.framework does not exist
import junit.framework.Assert;
                      ^
/app/src/main/java/com/marianhello/bgloc/service/LocationServiceIntentBuilder.java:164: error: cannot find symbol
        Assert.assertNotNull("Context can not be null!", mContext);
        ^
  symbol:   variable Assert
  location: class LocationServiceIntentBuilder
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s
    at ChildProcess.whenDone (/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by emc2spider** [comment]
I'm having the same issue, I was testing something else on my cordova configurations, and uninstalled/reinstalled the plugin which caused it to go from version alpha.38 to alpha.50 and now it stopped working.

Any way we can install an older revision from the v3 plugin?

**Comment by matthijsbierman** [comment]
Ran into the same problem trying to compile against cordova-android@8.0.0. Setting
```<preference name="android-targetSdkVersion" value="26" />```
did not fix the issue, still got:

```
app/platforms/android/app/src/main/java/com/marianhello/bgloc/service/LocationServiceIntentBuilder.java:164: error: cannot find symbol
        Assert.assertNotNull("Context can not be null!", mContext);
        ^
  symbol:   variable Assert
  location: class LocationServiceIntentBuilder```

**Comment by marcofuji** [comment]
> Ran into the same problem trying to compile against cordova-android@8.0.0. Setting
> `<preference name="android-targetSdkVersion" value="26" />`
> did not fix the issue, still got:
> 
> ```
> app/platforms/android/app/src/main/java/com/marianhello/bgloc/service/LocationServiceIntentBuilder.java:164: error: cannot find symbol
>         Assert.assertNotNull("Context can not be null!", mContext);
>         ^
>   symbol:   variable Assert
>   location: class LocationServiceIntentBuilder```
> ```

Same issue here. =/
