### ISSUE TITLE
Android service intent error, app crashing

### ISSUE THREAD

**Issue by Amsvartner** [mauron85/cordova-plugin-background-geolocation#554]
Notification handler needs updating to stop plugin from crashing the app on newer devices. One possible solution is to modify LocationService.java. I replaced line 242 with the following code:

```
// Build a Notification required for running service in foreground.
String channel;

if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
    NotificationManager mNotificationManager = (NotificationManager)  this.getSystemService(Context.NOTIFICATION_SERVICE);

    String name = "LocationService ";
    int importance = NotificationManager.IMPORTANCE_LOW;

    NotificationChannel mChannel = new NotificationChannel("LocationService channel", name, importance);

    mChannel.enableLights(true);
    mChannel.setLightColor(Color.BLUE);

    if (mNotificationManager != null) {
        mNotificationManager.createNotificationChannel(mChannel);
    } else {
        stopSelf();
     }

    channel = "LocationService channel";

} else {
    channel = "";
}

NotificationCompat.Builder builder = new NotificationCompat.Builder(this, channel);
```

Adding to the imports of the above mentioned file is necessary.

``` 
import android.app.Notification;
import android.app.NotificationChannel;
import android.app.NotificationManager;
```

**Comment by pashya98** [comment]
We are tried above solution but we are getting 

FATAL EXCEPTION: main
    Process: com.ballnowapp, PID: 2940
    java.lang.RuntimeException: Unable to stop service com.marianhello.bgloc.LocationService@edebe0b: java.lang.NullPointerException: Attempt to invoke interface method 'void com.marianhello.bgloc.LocationProvider.onDestroy()' on a null object reference
        at android.app.ActivityThread.handleStopService(ActivityThread.java:3718)
        at android.app.ActivityThread.access$1700(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1687)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6692)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.marianhello.bgloc.LocationProvider.onDestroy()' on a null object reference
        at com.marianhello.bgloc.LocationService.onDestroy(LocationService.java:188)
        at android.app.ActivityThread.handleStopService(ActivityThread.java:3698)
        at android.app.ActivityThread.access$1700(ActivityThread.java:200) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1687) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6692) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2019-03-05 16:54:23.506 2940-2993/com.ballnowapp I/com.marianhello.bgloc.LocationService: Network condition changed hasConnectivity: true
2019-03-05 16:54:23.510 2940-2940/com.ballnowapp E/UncaughtException: java.lang.RuntimeException: Unable to stop service com.marianhello.bgloc.LocationService@edebe0b: java.lang.NullPointerException: Attempt to invoke interface method 'void com.marianhello.bgloc.LocationProvider.onDestroy()' on a null object reference
        at android.app.ActivityThread.handleStopService(ActivityThread.java:3718)
        at android.app.ActivityThread.access$1700(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1687)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6692)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.marianhello.bgloc.LocationProvider.onDestroy()' on a null object reference
        at com.marianhello.bgloc.LocationService.onDestroy(LocationService.java:188)
        at android.app.ActivityThread.handleStopService(ActivityThread.java:3698)
        at android.app.ActivityThread.access$1700(ActivityThread.java:200) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1687) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6692) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by Amsvartner** [comment]
I would remove this issue thread if I could, I was unknowingly using an older version of the plugin which didn't support the latest version of android. Make sure you are using the latest alpha version, where this has been fixed.
