### ISSUE TITLE
BackgroundGeolocation is not defined on Visual Studio 2017

### ISSUE THREAD

**Issue by gabrielpotumati** [mauron85/cordova-plugin-background-geolocation#556]
* Plugin version: ~3.0.0-alpha.50
* Platform: iOS or Android
* OS version: Android 6.0
* Device manufacturer and model: Xaomi Redmi 3 PRO
* Plugin configuration options: 
* Link to your project:

## Context
function onDeviceReady() {

        document.addEventListener('pause', onPause.bind(this), false);
        document.addEventListener('resume', onResume.bind(this), false);

        BackgroundGeolocation.configure({
            locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
            desiredAccuracy: BackgroundGeolocation.MEDIUM_ACCURACY,
            stationaryRadius: 25,
            distanceFilter: 20,
            notificationTitle: 'Monitorando posição',
            notificationText: 'enabled',
            debug: true,
            interval: 10000,
            activityType: "AutomotiveNavigation",
            fastestInterval: 5000,
            activitiesInterval: 5000,
            stopOnTerminate: false, // true would probably suffice
            startOnBoot: true,
            startForeground: true, // not sure why this is needed
            pauseLocationUpdates: false, // I need location events in the background too; isn't that the whole point with this plugin?
            stopOnStillActivity: true, // hopefully it turns on again safely when moving
            saveBatteryOnBackground: false,
            url: "http://mstaxi.equipea.com.br/api/motorista_atualizar.ashx",
            postTemplate: {
                latitude: '@latitude',
                longitude: '@longitude',
                motorista: localStorage.getItem("motorista")
            }
        });

        BackgroundGeolocation.on('location', function (location) {
            console.log('location ' + location);
            // handle your locations here
            // to perform long running operation on iOS
            // you need to create background task
            BackgroundGeolocation.startTask(function (taskKey) {
                console.log('startTask ' + taskKey);
                // execute long running task
                // eg. ajax post location
                // IMPORTANT: task has to be ended by endTask
                BackgroundGeolocation.endTask(taskKey);
            });
        });
        

        BackgroundGeolocation.on('start', function () {
            console.log('[INFO] BackgroundGeolocation service has been started');
        });

## Actual Behavior
Native: tried calling BackgroundGeolocation.configure, but the BackgroundGeolocation plugin is not installed.

## Context
I am creating a project in Visual Studio 2017, I am not using any framework.

## Debug logs
ReferenceError: BackgroundGeolocation is not defined ...
ReferenceError: BackgroundGeolocation is not defined
at eval (eval at onResume (file:///android_asset/www/scripts/index.js:159:5), <anonymous>:1:1)
at onResume (file:///android_asset/www/scripts/index.js:159:5)

**Comment by gabrielpotumati** [comment]
After removed and add platform worked
