### ISSUE TITLE
Crash on Android 8.1

### ISSUE THREAD

**Issue by grimaldistudio** [mauron85/cordova-plugin-background-geolocation#620]
## Your Environment

* Plugin version: 2.3.6
* Platform:Android
* OS version: 8.1.0 API 27
* Device manufacturer and model: Ulefone Armor_x

* Running in Simulator:
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`): android 6.4.0
* Plugin configuration options: default
* Link to your project:

## Context

App crash only on android 8 if i use android-targetSdkVersion:28 while all right if i compile with android-targetSdkVersion:26

## Steps to Reproduce

1. app crash on start
2.
3.
4.

## Debug logs

 
    java.lang.RuntimeException: Unable to stop service com.marianhello.bgloc.LocationService@77fa03c: java.lang.NullPointerException: Attempt to invoke interface method 'void com.marianhello.bgloc.LocationProvider.onDestroy()' on a null object reference
        at android.app.ActivityThread.handleStopService(ActivityThread.java:3549)
        at android.app.ActivityThread.-wrap26(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1721)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.marianhello.bgloc.LocationProvider.onDestroy()' on a null object reference
        at com.marianhello.bgloc.LocationService.onDestroy(LocationService.java:188)
        at android.app.ActivityThread.handleStopService(ActivityThread.java:3531)
        at android.app.ActivityThread.-wrap26(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1721) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6523) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)

**Comment by grabkipower** [comment]
Did you add the <uses-permission android:name="android.permission.FOREGROUND_SERVICE" /> in the platform android config.xml ?

**Comment by grimaldistudio** [comment]
Tnx fore reply.
I tried to add android.permission.FOREGROUND_SERVICE but the problem persists.

actually the only solution is to set startForeground: false.

**Comment by mauron85** [comment]
Plugin version : 2.3.6 is tool old. Upgrade to 3.0.6 https://www.npmjs.com/package/@mauron85/cordova-plugin-background-geolocation

**Comment by grimaldistudio** [comment]
tnx fo reply.
i have upgraded to 3.0.6, but now there is another crash error:

 E/SQLiteDatabase: Error inserting altitude=325.4 bearing=0.0 latitude=XX.7132 accuracy=7.7 service_provider=1 speed=0.0 valid=1 has_speed=true provider=fused has_accuracy=true time=1568136841287 has_bearing=true batch_start=null radius=0.0 has_altitude=true has_radius=false mock_flags=10 longitude=XX.6098483
    android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)

**Comment by mauron85** [comment]
Try reboot device, maybe there are two instances of app running (one in some weird zombie state).

**Comment by grimaldistudio** [comment]
Hi,
i restarted the device but the problem persist.

E/SQLiteDatabase: Error inserting template=null sync_url= distance_filter=0 notification_icon_color= notifications_enabled=1 notification_icon_small= notification_text=ENABLED stop_terminate=1 debugging=0 start_boot=0 stop_still=1 service_provider=1 activities_interval=10000 url= stationary_radius=0.0 max_locations=10000 http_headers={} desired_accuracy=10 notification_title=Background tracking notification_icon_large= start_foreground=0 interval=60000 _id=1 fastest_interval=120000 sync_threshold=100
    android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:783)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1548)
        at android.database.sqlite.SQLiteDatabase.replace(SQLiteDatabase.java:1464)
        at com.marianhello.bgloc.data.sqlite.SQLiteConfigurationDAO.persistConfiguration(SQLiteConfigurationDAO.java:91)
        at com.marianhello.bgloc.BackgroundGeolocationFacade.persistConfiguration(BackgroundGeolocationFacade.java:456)
        at com.marianhello.bgloc.BackgroundGeolocationFacade.configure(BackgroundGeolocationFacade.java:343)
        at com.tenforwardconsulting.bgloc.cordova.BackgroundGeolocationPlugin$3.run(BackgroundGeolocationPlugin.java:177)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

**Comment by grimaldistudio** [comment]
Hi, tnx for reply.
I have found the problem for attempt to write a readonly database .
I have a procedure for clear temporary files data : window.ClearData.clear.
Now I have to figure out how to avoid the database reference.

**Comment by mauron85** [comment]
Glad to hear you resolved that problem. Is it working now?

**Comment by grimaldistudio** [comment]
it works great!
only one thing, in Object(location) I no longer receive the direction.

{"provider":"fused","locationProvider":1,"time":1568196239281,"latitude":xx.7132919,"longitude":xx.6095023,"accuracy":15.151000022888184,"altitude":331.5,"isFromMockProvider":false,"mockLocationsEnabled":false,"id":229}
