### ISSUE TITLE
npm ERR! Could not install from "@mauron85/cordova-plugin-background-geolocation@~3.0.7" as it does not contain a package.json file.

### ISSUE THREAD

**Issue by Taxi4you** [mauron85/cordova-plugin-background-geolocation#663]
```
**(...):cordova$ cordova platform rm ios**
Removing platform ios from config.xml file...
{ Error: npm: Command failed with exit code 1 Error output:
npm ERR! code ENOLOCAL
npm ERR! Could not install from "@mauron85/cordova-plugin-background-geolocation@~3.0.7" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/razbuchnik/.npm/_logs/2019-12-12T08_33_58_733Z-debug.log
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:189:13)
    at Pipe._handle.close (net.js:600:12)
  stderr:
   'npm ERR! code ENOLOCAL\nnpm ERR! Could not install from "@mauron85/cordova-plugin-background-geolocation@~3.0.7" as it does not contain a package.json file.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /Users/razbuchnik/.npm/_logs/2019-12-12T08_33_58_733Z-debug.log\n',
  code: 1 }
```

**Comment by vilasshetkar** [comment]
I'm facing same issue. Any updates?

**Comment by Taxi4you** [comment]
No updates yet

**Comment by mitLinkwok** [comment]
I am also facing the same issue.

**Comment by phoot** [comment]
any update same issue with 3.1.0 version

**Comment by marutifh** [comment]
Any update? Same issue.

**Comment by inameandy** [comment]
Same issue....

**Comment by chorpler** [comment]
I don't know if this will help anyone else, but I was getting this error earlier tonight and discovered that at some point, I ran a `cordova plugin add` command that created an erroneous entry in my `package.json` file. Under `dependencies` it had the following entry:

```json
  "cordova-plugin-background-geolocation": "@mauron85/cordova-plugin-background-geolocation@^3.1.0"
```

When it should have only had:

```json
    "@mauron85/cordova-plugin-background-geolocation": "^3.1.0",
```

Really not sure how I did that, but removing that line with the broken version field fixed it.
