### ISSUE TITLE
Cannot install the Plugin

### ISSUE THREAD

**Issue by gghangura** [mauron85/cordova-plugin-background-geolocation#726]
## Your Environment

* Plugin version:3.1.0
* Platform: Android
* OS version: 
* Device manufacturer and model:

* Running in Simulator:
* Cordova version (`cordova -v`): 9.0.0 (cordova-lib@9.0.1)
* Cordova platform version (`cordova platform ls`): android 8.1.0, ios 5.1.1
* Plugin configuration options: 
* Link to your project:

## Context

When I try to run the command "cordova plugin add @mauron85/cordova-plugin-background-geolocation", I get the following error. 

gurjitghangura@gghangura:~/Documents/git/Owlshead$ cordova plugin add @mauron85/cordova-plugin-background-geolocation
Installing "cordova-plugin-background-geolocation" for android
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-background-geolocation': CordovaError: Uh oh!
"/Users/gurjitghangura/Documents/git/Owlshead/platforms/android/cordova-plugin-background-geolocation/gpsapp-dependencies.gradle" already exists!
    at copyNewFile (/Users/gurjitghangura/Documents/git/Owlshead/platforms/android/cordova/lib/pluginHandlers.js:234:45)
    at install (/Users/gurjitghangura/Documents/git/Owlshead/platforms/android/cordova/lib/pluginHandlers.js:80:17)
    at ActionStack.process (/Users/gurjitghangura/Documents/git/Owlshead/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/Users/gurjitghangura/Documents/git/Owlshead/node_modules/cordova-common/src/PluginManager.js:112:24)
    at PluginManager.addPlugin (/Users/gurjitghangura/Documents/git/Owlshead/node_modules/cordova-common/src/PluginManager.js:142:21)
    at /Users/gurjitghangura/Documents/git/Owlshead/platforms/android/cordova/Api.js:210:74
    at _fulfilled (/Users/gurjitghangura/Documents/git/Owlshead/node_modules/q/q.js:854:54)
    at /Users/gurjitghangura/Documents/git/Owlshead/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/Users/gurjitghangura/Documents/git/Owlshead/node_modules/q/q.js:816:13)
    at /Users/gurjitghangura/Documents/git/Owlshead/node_modules/q/q.js:877:14
Uh oh!
"/Users/gurjitghangura/Documents/git/Owlshead/platforms/android/cordova-plugin-background-geolocation/gpsapp-dependencies.gradle" already exists!

## Expected Behavior
The command should install the plugin

## Actual Behavior
The command does not install the plugin and throws an error

## Steps to Reproduce

I am not too sure how to reproduce it
1.
2.
3.
4.

## Context

I am trying to use this plugin to test the location features in Android. And update the UI of the User Location.

**Comment by peechyfloof** [comment]
Hey,

you just need to delete the platforms folder, then reinstall (If you haven´t already)
