### ISSUE TITLE
Conflict plugin cordova-plugin-background-geolocation installed

### ISSUE THREAD

**Issue by jasonfish568** [mauron85/cordova-plugin-background-geolocation#756]
## Your Environment

* Plugin version: 3.1.0
* Platform: Android
* OS version: Any
* Device manufacturer and model: Not related
* Running in Simulator: Not related
* Cordova version (`cordova -v`): 10.0.0
* Cordova platform version (`cordova platform ls`): android 9.1.0
* Plugin configuration options: Not related
* Link to your project:

## Context
This brought up my attention when build using Ionic Appflow. When doing cordova platform add android, the program detects plugin cordova-plugin-background-geolocation and installs it. However, it installed the original cordova-plugin-background-geolocation plugin not @mauron85/cordova-plugin-background-geolocation even though I only have @mauron85/cordova-plugin-background-geolocation listed in the package.json. Then in the plugins folder, cordova-plugin-background-geolocation is now the incorrect version.

## Expected Behavior
The program should not add cordova-plugin-background-geolocation but use @mauron85/cordova-plugin-background-geolocation.

## Actual Behavior
Both cordova-plugin-background-geolocation and @mauron85 are installed by npm but ionic plugins folder has cordova-plugin-background-geolocation because due to the ordering index it's added later than @mauron85/cordova-plugin-background-geolocation.

## Possible Fix
Not known. But remove @mauron85/cordova-plugin-background-geolocation and  cordova-plugin-background-geolocation from package.json before adding android platform, then add it after adding the platform can make it work. 

## Steps to Reproduce
1. Clean up project by ```cordova platform rm android```
2. Remove plugins and node_modules folder
3. run ```npm install```
4. run ```cordova platform add android```
5. run ```cordova build android``` then an error msg pops up saying Java Http not found

## Context
Unable to build using Appflow.

## Debug logs
> Task :app:compileDebugJavaWithJavac FAILED
.../platforms/android/app/src/main/java/com/zencity/cordova/bgloc/LocationUpdateService.java:6: error: package org.apache.http does not exist
import org.apache.http.HttpResponse;
                      ^
.../platforms/android/app/src/main/java/com/zencity/cordova/bgloc/LocationUpdateService.java:7: error: package org.apache.http.client.methods does not exist
import org.apache.http.client.methods.HttpPost;
                                     ^
.../platforms/android/app/src/main/java/com/zencity/cordova/bgloc/LocationUpdateService.java:8: error: package org.apache.http.entity does not exist
import org.apache.http.entity.StringEntity;
                             ^
.../platforms/android/app/src/main/java/com/zencity/cordova/bgloc/LocationUpdateService.java:9: error: package org.apache.http.impl.client does not exist
import org.apache.http.impl.client.DefaultHttpClient;
                                  ^
.../platforms/android/app/src/main/java/com/zencity/cordova/bgloc/LocationUpdateService.java:662: error: cannot find symbol
            DefaultHttpClient httpClient = new DefaultHttpClient();
            ^
  symbol:   class DefaultHttpClient
  location: class LocationUpdateService

**Comment by ktoala** [comment]
same error :/

**Comment by jasonfish568** [comment]
This error came up recently I believe, my appflow build in June did get through with no error.

**Comment by chg7896** [comment]
Did you solve this?
Even adding a platform doesn't work for the same problem.

**Comment by chg7896** [comment]
Did you solve this?
Adding a platform doesn't work for the same problem.

**Comment by jasonfish568** [comment]
> Did you solve this?
> Adding a platform doesn't work for the same problem.

No mate. Planning to move onto alternative plugin.

**Comment by chg7896** [comment]
@mauron85 
Sorry but do you know about this issue?

**Comment by chg7896** [comment]
What the... In my case

When I type `ionic cordova platform add android`
Show this error

============================================================
Discovered plugin "cordova-plugin-mauron85-background-geolocation". Adding it 
to the project
Installing "cordova-plugin-mauron85-background-geolocation" for android
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-mauron85-background-geolocation': CordovaError: Uh oh!
"C:\Users\user1\Documents\GitHub\apps\platforms\android\app\src\main\java\com\marianhello\bgloc\cordova\ConfigMapper.java" already exists!
    at copyNewFile (C:\Users\user1\Documents\GitHub\apps\platforms\android\cordova\lib\pluginHandlers.js:231:45)
    at install (C:\Users\user1\Documents\GitHub\apps\platforms\android\cordova\lib\pluginHandlers.js:34:17)
    at ActionStack.process (C:\Users\user1\Documents\GitHub\apps\platforms\android\cordova\node_modules\cordova-common\src\ActionStack.js:56:25)
    at PluginManager.doOperation (C:\Users\user1\Documents\GitHub\apps\platforms\android\cordova\node_modules\cordova-common\src\PluginManager.js:112:24)    at PluginManager.addPlugin (C:\Users\user1\Documents\GitHub\apps\platforms\android\cordova\node_modules\cordova-common\src\PluginManager.js:142:21)  
    at C:\Users\user1\Documents\GitHub\apps\platforms\android\cordova\Api.js:161:78
    at processTicksAndRejections (internal/process/task_queues.js:93:5)       
Uh oh!
"C:\Users\user1\Documents\GitHub\apps\platforms\android\app\src\main\java\com\marianhello\bgloc\cordova\ConfigMapper.java" already exists!
[ERROR] An error occurred while running subprocess cordova.

        cordova.cmd platform add android --save exited with exit code 1.      

        Re-running this command with the --verbose flag may provide more      
        information.

============================================================

but ignore and type `ionic cordova run android`
Works without problems.
I don't know if other related plugins have errors, but the background geolocation function seems to work without any problem.
