### ISSUE TITLE
Android crash on start

### ISSUE THREAD

**Issue by coyu1314** [mauron85/cordova-plugin-background-geolocation#89]
I am experiencing a crash on app start issue on the following android version: 6.0.1, 4.3.2, 4.2.2. basically, it crash whenever app is open. I tried both locationService ANDROID_DISTANCE_FILTER and ANDROID_FUSED_LOCATION. still crashes. Please advise. thanks 

here's the config of the bg location 

```
backgroundGeoLocation.configure(callbackFn, failureFn, {
            desiredAccuracy:                        10,
            stationaryRadius:                       150, //20, //150,                //production should be 150
            distanceFilter:                         $scope.dist2sync*1000,         //test val= 30 or 50 meters
            stopOnTerminate:  true, // <-- enable this to clear background location settings when the app terminates
            locationService: backgroundGeoLocation.service.ANDROID_DISTANCE_FILTER, //ANDROID_DISTANCE_FILTER or ANDROID_FUSED_LOCATION (may causing crash if using fused)
//            interval: 60000, // <!-- poll for position every minute on ANDROID_FUSED_LOCATION only
//            fastestInterval: 120000, //on ANDROID_FUSED_LOCATION only
            
            debug:                                  false, // <-- enable this hear sounds for background-geolocation life-cycle.
            useSignificantChangesOnly:              true,   // ios only, change location only when cell tower change is detected
            locationUpdateInterval:                 60000,       // in miliseconds, default it to 30000 for test
            fastestLocationUpdateInterval:          60000,       // prod =: 60 sec; test: 30000 = 30 sec
            activityRecognitionInterval:            45000,      // millis, default 10000 = 10 sec
//            stopTimeout:                            5,          // Wait x miutes to turn off location system after stop-detection
            activityType:                           'AutomotiveNavigation',
            notificationText:                       "Location tracking is active",
            notificationTitle:                      "Location Service"
        });
```

**Comment by uzumakinaruto123** [comment]
This is probably because of the launchmode : singleTask. 
When you use launchmode like singleTask or singleTop you need to implement `onNewIntent()` in activity along with `onCreate()`  .

Check the behaviour on different android versions here : 

> https://inthecheesefactory.com/blog/understand-android-activity-launchmode/en

**Comment by mauron85** [comment]
We need to fix this.

**Comment by uzumakinaruto123** [comment]
sure I can try but am confused on what the issue actually is. :p

Ever since that multiple instance issue was created , i am not able to understand that.
what i did is 

1. installed app and opened from menu.
2. clicked home. (not killed)
3. again i opened it from menu.
4. repeated 3 to 4 times.

Its true sometimes it records multiple locations but the count was not consistent. even after opening 3 to 4 times some locations were recorded only once.

Regarding , the launchmode.. 

In sampleapp, I changed launchmode to `singleTask` and app works totally fine without any `onNewIntent()` implementation. 

`<preference name="AndroidLaunchMode" value="singleTask" />`

I dont have any other version other than android 4.2.2 to test.

**Comment by mauron85** [comment]
I mean to fix only the crash by implementing missing methods. 👍

**Comment by coyu1314** [comment]
hmm... I not so sure if it's really caused by the singleTask because here's what I found after some testing. I tried removing the 
```
<gap:config-file platform="android" parent="/manifest/application">
        <activity android:launchMode="singleTask" />
    </gap:config-file>
```

as well as tried all four activity types(standard, SingleTask, SingleTop, SingleInstance). I am still getting the same crash on start issue. 

I found one thing really interesting is that if I install an older version of my app(this app was using version "0.4.2" bg location plugin), then install the new version(with this plugin), it wouldn't crash. 

but if I 

- reinstall the new version on top of the new version

- or uninstall whatever version I have and install the new version directly

the crash on start issue will come back. Hope this will help. It's funny that this plugin is being used by so many developers but how come I am the only one getting this kind of weird issue?  I don't know if something is wrong with my config.xml

here's my config.xml. And Thank you again for your help. 


```

<widget xmlns="http://www.w3.org/ns/widgets" xmlns:gap="http://phonegap.com/ns/1.0" xmlns:android="http://schemas.android.com/apk/res/android" id="com.xxx" version="1.0.0">
    <name>app name</name>
    <description>app name dsc</description>
    <author email="xxxx@gmail.com" href="http://xxxx.com">xxxx</author>
    <access origin="*"/>
    
    
    <gap:config-file platform="android" parent="/manifest/application">
        <activity android:launchMode="singleTask" />
    </gap:config-file>
    <preference name="fullscreen" value="false"/>
    <preference name="webviewbounce" value="false" />
    <preference name="UIWebViewBounce" value="false" />
    <preference name="DisallowOverscroll" value="true" />
    
    <!--Target Android Device-->
    <preference name="android-minSdkVersion" value="14" />
    <preference name="android-targetSdkVersion" value="14" />
    
    <!-- Android  icons -->
    ....
   
    <!-- Splash Screen -->
    ...
    
    <preference name="SplashScreen" value="img/screen/android/drawable/screen.png" />
    <preference name="SplashScreenDelay" value="6000" />
    <preference name="SplashMaintainAspectRatio" value="true" />
    <preference name="android-build-tool" value="gradle" />
    <feature name="Geolocation">
        <param name="ios-package" value="CDVLocation" />
    </feature>
    <gap:platform name="ios" />
    <gap:platform name="android" />
    
    
    <plugin name="phonegap-plugin-push" spec="1.5.3" source="npm" > <!-- Currently only 1.5.3 will work on ios. latest version 1.6.3 doesnt work. -->
        <param name="SENDER_ID" value="xxx" />
    </plugin>
    
    
    <plugin name="cordova-plugin-geolocation" source="npm" spec="2.2.0"/>
    <!-- bg location from mauron85 -->
    <!--<gap:plugin name="cordova-plugin-mauron85-background-geolocation" source="npm" version="0.4.2"/>-->
    <!--For Android, use this instead of the custom message from bitbucket. Otherwise, it will cause android to crash-->
    <!-- as of now spec="1.0.1"-->
    <plugin name="cordova-plugin-mauron85-background-geolocation" source="npm"/>    
    <gap:plugin name="dk.interface.cordova.plugin.googlenavigate" version="0.1.2" />
    <gap:plugin name="nl.x-services.plugins.insomnia" version="4.0.1" />
    <gap:plugin name="nl.x-services.plugins.toast" version="2.0.2" />
    <gap:plugin name="cordova-plugin-whitelist" source="npm" />
    <gap:plugin name="org.apache.cordova.device" version="0.2.12" source="npm" />
    <gap:plugin name="cordova-plugin-file"  source="npm" version="1.3.1"/>
    <gap:plugin name="cordova-plugin-media"  source="npm" version="0.2.13"/>
    <gap:plugin name="org.apache.cordova.vibration" source="npm" />
    <gap:plugin name="org.apache.cordova.inappbrowser" source="npm"/>
    <gap:plugin name="org.apache.cordova.dialogs" source="npm"/>
    <gap:plugin name="org.apache.cordova.splashscreen" source="npm"/>
    <gap:plugin name="uk.co.workingedge.phonegap.plugin.launchnavigator" source="npm" />
    <gap:plugin name="hu.dpal.phonegap.plugins.uniquedeviceid" version="1.2.0" />
    <gap:plugin name="com.phonegap.plugins.barcodescanner"/>
</widget>

```

**Comment by uzumakinaruto123** [comment]
Try monitoring the app using android device monitor (adm) that will save a lot of time. you will know the exact location of the app crash.

**Comment by coyu1314** [comment]
I found these from the log using ADM. I am not a java-man, not sure what this is and how to fix it. Do you guys have any idea what this is about? Thank you

```

06-13 12:42:02.664: E/AndroidRuntime(8094): FATAL EXCEPTION: pool-2-thread-2
06-13 12:42:02.664: E/AndroidRuntime(8094): Process: com.cabbus.driver_app, PID: 8094
06-13 12:42:02.664: E/AndroidRuntime(8094): java.lang.IncompatibleClassChangeError: The method 'java.io.File android.support.v4.content.ContextCompat.getNoBackupFilesDir(android.content.Context)' was expected to be of type virtual but instead was found to be of type direct (declaration of 'com.google.android.gms.iid.zzd' appears in /data/app/com.cabbus.driver_app-2/base.apk)
06-13 12:42:02.664: E/AndroidRuntime(8094): 	at com.google.android.gms.iid.zzd.zzeb(Unknown Source)
06-13 12:42:02.664: E/AndroidRuntime(8094): 	at com.google.android.gms.iid.zzd.<init>(Unknown Source)
06-13 12:42:02.664: E/AndroidRuntime(8094): 	at com.google.android.gms.iid.zzd.<init>(Unknown Source)
06-13 12:42:02.664: E/AndroidRuntime(8094): 	at com.google.android.gms.iid.InstanceID.zza(Unknown Source)
06-13 12:42:02.664: E/AndroidRuntime(8094): 	at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
06-13 12:42:02.664: E/AndroidRuntime(8094): 	at com.adobe.phonegap.push.PushPlugin$1.run(PushPlugin.java:73)
06-13 12:42:02.664: E/AndroidRuntime(8094): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
06-13 12:42:02.664: E/AndroidRuntime(8094): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
06-13 12:42:02.664: E/AndroidRuntime(8094): 	at java.lang.Thread.run(Thread.java:818)
06-13 12:42:02.664: E/AbstractTracker(8094): Can't create handler inside thread that has not called Looper.prepare()
06-13 12:42:02.664: D/AppTracker(8094): App Event: crash
06-13 12:42:02.672: E/AbstractTracker(8094): mTrackerAsyncQueryHandler is null

```

**Comment by uzumakinaruto123** [comment]
Honestly , even i dont understand this one. but error is ,

`java.lang.IncompatibleClassChangeError: The method 'java.io.File android.support.v4.content.ContextCompat.getNoBackupFilesDir(android.content.Context)' was expected to be of type virtual but instead was found to be of type direct (declaration of 'com.google.android.gms.iid.zzd' appears in /data/app`

[Link](https://www.google.co.in/search?q=java.lang.IncompatibleClassChangeError%3A+The+method+%27java.io.File+android.support.v4.content.ContextCompat.getNoBackupFilesDir(android.content.Context)%27+was+expected+to+be+of+type+virtual+but+instead+was+found+to+be+of+type+direct+(declaration+of+%27com.google.android.gms.iid.zzd%27+appears+in+%2Fdata%2Fapp&ie=utf-8&oe=utf-8&client=firefox-b-ab&gfe_rd=cr&ei=f-deV83UKcnC8gfLrbLgCw)
simply google it. all stackoverflow links are related to this one. and its related to play services version being out of sync with some other dependency.

**Comment by mauron85** [comment]
Actually it crashed PlusPlugin, so it's not our issue :-)

```
at com.adobe.phonegap.push.PushPlugin$1.run(PushPlugin.java:73)
```
