### ISSUE TITLE
Build failed after reinstalling the plugin @next

### ISSUE THREAD

**Issue by ramveersgh** [mauron85/cordova-plugin-background-geolocation#93]
I tried to update plugin by removing and adding from following command
`cordova plugin add cordova-plugin-mauron85-background-geolocation@next`

Its added successfully but giving following error on build for android.
```
:transformClassesWithDexForDebug
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lorg/apache/cordova/AuthenticationToken;
 FAILED
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)



FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_91\bin\java.exe'' finished with non-zero exit value 2
```
Are there any dependency update din current version?
Please  help..

**Comment by ronakkaria** [comment]
Refer to Multidex section in Readme. Most likely due to another plugin you installed in the interim

**Comment by mauron85** [comment]
Also do not use @next to instal 2.0.0. Next branch is only for dev versions. Need to update instruction on npm . Will release rc4 just to update instruction.

Install:
```
cordova plugin add cordova-plugin-mauron85-background-geolocation
```

**Comment by ramveersgh** [comment]
@mauron85 
Thanks for the information. I will update to 2.0.0 and will check if it resolve the issue.
